= Genealogy Research
:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/skins 
:nofooter:


TODO: Organize by topic not facility or location

include::inc/nara.adoc[]

== Guides
* https://www.familysearch.org/en/wiki/\[FamilySearch wiki]
  - Germany Genealogy https://www.familysearch.org/en/wiki/Germany_Genealogy[section] 
  - https://www.familysearch.org/en/wiki/index.php?title=Allen_County,_Indiana_Genealogy[Allen County, Indiana] section.

* Genealogy Center guide to https://acpl.lib.in.us/images/Documents/Gendocs/allencountyincongregations.pdf[Allen County, Indiana, Congregational Records, Histories and Directories]

* Genalogy Center Snapshots guides:
  - https://acpl.lib.in.us/pathfinders/snapshots/subjects[Subject Snapshots] includes a German guide.
  - https://acpl.lib.in.us/pathfinders/snapshots/states[State Snapshots] are State research guides.
  - https://acpl.lib.in.us/images/Documents/Gendocs/States/allen-county-fort-wayne-sg.pdf[Allen Co. & Ft. Wayne IN] is a separate guide with the State sanpshot guides.

* The InGenWeb site for Allen County has this info on https://www.acgsi.org/genweb/county/records/land-records-allen-county-indiana.html[Land Records] for Allen County.

* https://irenehansen11.files.wordpress.com/2015/04/pre-1850-in-research.pdf[Pre-1850 Indiana Resources for Family History Research] by Irene Hansen, Reference Librarian Indiana State Library

* https://www.familysearch.org/en/help/helpcenter/lessons/old-german-script-part-1[Old German Script] 3-part video series by FamilySearch

=== PERSI

https://www.genealogycenter.info/persi/[persi]

=== Land Tools

https://glorecords.blm.gov/search/default.aspx?searchTabIndex=0&searchByTypeIndex=4[Indiana Tract Books at Bureau of Land Management, General Land Office Records]

=== City Directories

They can be used tin conjunction with other records to ananylze potential relationships  between individuals. The information from several years should be used and compared. Someone who is the 
widow (dsingated `(wid)` ) of, say, A. Darah, in one year and later listed as the widow of Newton Darah a few years later may be the widow of 'Alvin Newton Darah', which a marriage record
of their son or duaghter may confirm.

Directories may also list businesses in the same line of work. In the case of Fort Wayne City Directories from the 1860s and later, the Wards of the city are described by their street boundaries.

Search 'City Direcctories' or 'City Directory' on sites like: 

* https://archive.org[Internet Archive]
* https:///www.hathitrust.org[Hathi Trust]
* https://dp.la/[Digital Public Library of America]
* https://www.myheritage.com/research/collection-90100/compilation-of-published-sources[MyHeritage's compliaton of poublished sources.
* PFW Mastadon Digital Object Network, which has digitized mpas, books, etc

  - https://mdon.library.pfw.edu/digital/collection/cc_fw_hist/search[Fort Wayne Area HIstory Collection]
  - https://mdon.library.pfw.edu/digital/collection/cc_acfwhs/search[History Center Digital Collections]
* Ancestry's U.S. City Direcories https://www.ancestry.com/search/collections/2469/[search page]

=== PLSS Tools

.Table of Allen County, Indiana, township names and their PLSS township and range designation.
[width="45%",rows="grid", frame="none"]
|===
|Township|Range|Name

|29 North|11 East|Lafayette

|29 North|12 East|Pleasant

|29 North|13 East|Marion

|29 North|14 East|Madison

|29 North|15 East|Monroe

|30 North|11 East|Aboite

|30 North|12 East|Wayne

|30 North|13 East|Adams

|30 North|14 East|Jefferson

|30 North|15 East|Jackson

|31 North|11 East|Lake

|31 North|12 East|Washington

|31 North|13 East|St. Joseph

|31 North|14 East|Milan

|31 North|15 East|Maumee

|32 North|11 East|Eel River

|32 North|12 East|Perry

|32 North|13 East|Cedar Creek

|32 North|14 East|Springfield

|32 North|15 East|Scipio
|===

The https://www.acres.co/plat-map[www.acres.co/plat-map] site shows a map with townships and ranges and their township names.

=== Allen County, Indiana, township Histories

TODO:

==== Browsing Ship Passenger Lists

Ship arrival Passneger Lists can be browsed by date or by roll at this Ancestry page https://www.ancestry.com/search/collections/7488/[https://www.ancestry.com/search/collections/7488/]. 
See the column on the right side.

==== Old German Typefaces and Handwriting

- FamilySearch Old German Script https://familysearch.brightspotcdn.com/fc/1d/865daadf23b9270f0d67c643a099/old-german-script-handout.pdf[handout]
- https://germangirlinamerica.com/old-german-cursive-alphabet-and-typefaces/[https://germangirlinamerica.com/old-german-cursive-alphabet-and-typefaces/]

== Genealogists and Experts

* Germanic Genealogical Society's https://ggsmn.org/cpage.php?pt=19[translators list].
 
* https://www.berufsgenealogie.net/[Verband deutschsprachiger Berufsgenealogen e.V.] is the Association of German-speaking Professional Genealogists.

* https://iggp.org/index.php[International German Genealogical Partnership] has a list of https://iggp.org/index.php[Professional Researchers]

* https://www.apgen.org[Association of Professional Genalogists]. Note: It is not a certifying organization.

* https://www.familysearch.org/en/rootstech/session/certified-genealogist-and-accredited-genealogist-a-comparison[BCG vs ICAPGen] certification  

* https://dagv.org/?Die_DAGV[Deutsche Arbeitsgemeinschaft genealogischer Verbände (DAGV)]

== Indiana State Archives

* The https://www.in.gov/iara/divisions/state-archives/collections/[Collections] of the https://www.in.gov/iara/divisions/state-archives/[Indians State Archives] includes subjects like: 

- https://www.in.gov/iara/divisions/state-archives/collections/[Land Records in Indiana], which explains when the *Fort Wayne Federal Land Office* was opened:

____
As the tide of settlement (in Indiana) moved north, a new land office opened at Fort Wayne in 1823. It sold lands in all or part of the present day counties of [.underline]#Adams, Allen#, Blackford, Cass, Clinton,
DeKalb, Delaware, Grant, Howard, Huntington, Jay, Kosciusko, Lagrange, Madison, Miami, Noble, Randolph, Steuben, Tipton, Wabash, Wells, and Whitley. [.underline]#The final sales were in 1852; all lands remaining unsold
were attached to the Indianapolis Land Office#.
____

See state archives https://www.in.gov/iara/divisions/state-archives/collections/land-records/major-land-record-collection-descriptions/[Major Land Record Collection Descriptions].

- https://www.in.gov/iara/divisions/state-archives/collections/naturalization-records/[Naturlatizatoin Records]. 

This section describes the naturalization records digitalization efforts and where nationarlization records can be found. It explains the naturalization process:
____
In the nineteenth century and most of the twentieth century, naturalization was a three step process. First, one declared intention to naturalize, then petitioned
for naturalization, and lastly, received a certificate or a court order granting citizenship.

*Declarations and Petitions*

The first two steps involved the submission of specific documents -- declarations of intent and petitions -- that the Archives now holds for some counties.

If the individual you are looking for is not listed in the database, it will be necessary to know the county or counties in which the naturalization process began.

Please note that many immigrants never completed the full process. In the nineteenth century, many states allowed their residents to buy land and work without obtaining full citizenship.
[.underline]#In Indiana, one could purchase land, own a business, and vote with a declaration of intention.#

*Final Papers*

After 1907, the federal government required state/local courts to issue standardized certificates of citizenship, to send duplicate copies of the certificates to the federal government, and to retain a certificate stub for their own court records. The Archives has certificate stubs for a few counties. These stubs are organized by date, not alphabetically; thus, a date of naturalization or a certificate number is imperative to locating any individual's certificate stub.

Many counties recorded the final process on the back of the petitions; therefore an additional “final paper” will not be available in the Archives.
____

== Genealogy Center

include::inc/gen-center.adoc[]

=== Steve Morse

https://stevemorse.org[stevemorse.org]

=== Allen County Genealogical Society of Indiana(ACGSI)

The Members-Only section has a wealth of resources for Allen County, Indiana.

* https://www.acgsi.org/records.php[ACGSI web page]

* ACGSI https://www.acgsi.org/deed/index.asp[Deed Index (1870s-1890s)] 

== German 

include::inc/german-research.adoc[]
