= Analysis of Rootsmagic Database

== Analysis of Main Tables Describing Persons, Names, and Relationshiups

The `PersonTable.PersonID` is the key for all unique individuals in a
tree. In a addition to the `PersonID` key, the unique `UniqueID` column
is likely a `GUID` of some sort, perhaps related to GEDOM field?

.Table 1. PersonTable
[width="99%",cols="19%,7%,4%,6%,6%,5%,6%,6%,5%,5%,7%,5%,6%,5%,8%",]
|===
|PersonID Int (Prim Key) |UniqueID TEXT |Sex Int |ParentID Int |SpouseID
Int |Color Int |Relate1 Int |Relate2 Int |Flags Int |Living Int
|IsPrivate Int |Proof Int |Bookmark Int |Note TEXT |UTCModDate Float
|===

The `NameTable` has key `NameID` that uniquely identifies every nane
used in the tree. These are each person's main names and any alternate
names they have. Each row of the `NameTable` also has an `OwnerID`
desginating to whom the name belongs. This is a foregin key that no
doubt maps to `PersonTable.PersonID`. This derives from the fact that
1.) the count of `OnwerID` s is equal to the count of the `PersonID`s ,
the unique persons in the tree, and 2.) this links the Person with
unique `PersonID` to the name(s), which must be done.

It appears that the first `NameID`, of the set of `NameID` s that all
have the same `OnwerID`, is the "main" name used, and the subsequents
names in the set are the 'alternate' names.

Thus a person in the `PersonTable` identified by their `PersonID` has a
"main" name, but can also have several alternate names. These are
usually just given names rather than surnames.

.Table 2. NameTable
[width="99%",cols="17%,3%,4%,3%,3%,3%,4%,4%,3%,5%,4%,4%,3%,4%,3%,4%,4%,3%,4%,5%,4%,4%,5%",]
|===
|NameID Int (Prim Key) |OwnerID Int |Surname TEXT |Given TEXT |Prefix
TEXT |Suffix TEXT |Nickname TEXT |NameType Int |Date TEXT |SortDate
BigInt |IsPrimary Int |IsPrivate Int |Proof Int |Sentence TEXT |Note
TEXT |BirthYear Int |DeathYear Int |Display Int |Language TEXT
|UTCModDate Float |SurnameMP TEXT |GivenMP TEXT |NicknameMP TEXT
|===

The `FamilyTable` has a primary key of `FamilyID`. The columns
`FatherID` and `MotherID` are no doubt foreign keys that map to
`PersonTable.PersonID`. The pair `FatherID` plus `MotherID` is also
mostly likely unique since the children from the same couple are cpart
of the same family entity, even if the family is not a traditional
nuclear family or even one in which the children grow up. Every child
has a unique set of father and mother. I’m not sure if the `FamilyTable`
only models couples that have chilren? Some couples (either
intentionally or otherwise) have no children.

If a mother or father is unknown it appears that their `FatherID` or
`MotherID` is 0.

A FamilyTable allows us to model the fact that a specific mand or a
specific woman may have children by more than one person, more than one
`PersonID`.

The `NameTable` also has the `BirthYear` and `DeathYear`.
.Table 3. FamilyTable
[width="99%",cols="18%,5%,5%,4%,5%,5%,5%,4%,6%,6%,6%,7%,7%,7%,4%,6%",]
|===
|FamilyID Int (Prim Key) |FatherID Int |MotherID Int |ChildID Int
|HusbOrder Int |WifeOrder Int |IsPrivate Int |Proof Int |SpouseLabel Int
|FatherLabel Int |MotherLabel Int |SpouseLabelStr TEXT |FatherLabelStr
TEXT |MotherLabelStr TEXT |Note TEXT |UTCModDate Float
|===

The concept of a child and children is modelled by the `ChildTable`.
Each child in this table has a unique `RecID`. The `ChildID` is no doubt
a foreign key that maps to `PersonID`. There is also a `FamilyID` that
no doubt is a foreign key that maps to `FamilyTable.FamilyID`. All
children with the same `FamilyID` belong to the same family in the sense
that they have the same set of parents.

Perhaps not every person in a tree yet has an idenitifable set of
parents. In this case, there would be no entry for them in the
`ChildTable` or `FmailyTable`.

.Table 4. ChildTable
[width="97%",cols="16%,14%,14%,14%,14%,14%,14%",]
|===
|RecID Int (Prim Key) |ChildID Int |F amilyID Int |Re lFather Int |Re
lMother Int |Chi ldOrder Int |Is Private Int
|===


== Analysis of Tables Related to Downloaded Ancestry Media Files
