== Research Leads and Hints for German Families in Allen county

A summary of some findings and possible connections to research further

The biography of *Frederick W. Fahlsing*, on page 295, of The History of the Maumee River Basin, Volume 3. details:

- Birth in Minden
- Parents immigration in 1844, settled in Preble twp, Adams CO., members of German Lutheran church; siblings names given
- marriage to Mary Hetzman, born in Minden.
  * One year after the marriage he moved to Wayne twp, Allen CO.
  * Mary's father emigrated in 1837 and *Mr Hetzman worked on the Erie Canal, in the state of New York!*
  * Mr Hetzman relocated to Washington twp, Allen CO, in 1842.
  ** His wife and children emigrated in 1845.
  ** His childrens names are given

- The newspaper obituary of the young child of William bender

The biography of *Henry Beerman*, on page 299, of The History of the Maumee River Basin, Volume 3. details:

- born in *Glesse, Darmstadt, German, in 1853* but *is that correct? Aren't the Behrman's from north German?*
- Family emigrated in 1855.
- Married *Johanna Rühl* in 1874, who was born in Frankfort-am-Main.

According to my Ancestry entry for him, he was born in Glesse, Ottenstein, Niedersachsen or Glesse, Holzminden, Ottenstein Braunschweig, Niedesachsen.

In the 1860 census, the family is listed as "Buchfind", and they lived next to *another "Buchfind" family, with several members!* And both "Buchfind" families head of household have the
same occupation of "Com Lab".

TODO: 

- Double check that I have the correct Passenger List and its correct page.
- Where they two Beerman families on the ship? And on different pages of the passenger list?
- Add the other Beerman family next door in the 1860 censys

TODO: 

- Include the information in the surname subfolders here in a general summary.
- Read the family histories about and look for Fahlsing, Wiebke, and other family histories as part of preliminary research.

