== Summary of Immigrants from Rodehim-Bieber, Grand Duchy of Hessen, and nearby Fellinghausen in Marion twp, Allen CO, Indiana

Fellinghausen is a small village a short distance from the larger village of Rodhein an der Bierber (Rodheinm on the Bieber river), which today is called
Rodheim-Bieber. 

Two Bender families from Fellinghausen, in the Grand Duchy of Hessen, most certainly brothers--although their common
parentage still needs to be confirmed beyon doubt--married two Rühl sisters (whose parentage likewise needs to be confirmed). 
Both Bender families eventually settled in Marion twp, Allen CO, around 18XX. 

Later the Joahnn Jakob Peppler family, from Rodheim an der Bieber, would emigrated and also settle in Marion township, Allen couty, Indiana. On 11 June 1863, the Peppler's oldest
son Ludig "louis" Peppler (1843-1914) married the 4th daughter of Johannes Bender, Marie Anna Bender (1846-1931).

When the Johann Jokab Peppler family emigrated from Rodheiom-Bieber, who was about the same age as the Benders, emigrate, in April 1857, other individuals from
Rodheim were on the same ship  left Brmen??? and arrived in NYC. This included Dudenhöfers and possibly Dönges. It is unclear if these Dudenhöfers settled
in Allen CO. There are Dudenhöfers who did, but it is unclear how and if they are relatived to those on the ship, in 1857, with the Pepplers.

Emigrants from Rodheim-Bieber, Heseen, and nearby Fellinghausen settled in Allen County, Indiana. 

* peppler-bender

The daughter of Johannes Bender, Mary XXX Bender ( ), married the oldest son of Johann Jocab Peppler and XXX Magdalene Plat, Ludwig "Louis"
Peppler (  )twho came from Fellinghausen and Rodheim-Bieber. 

T
The Pepplers emigrate April 1857, along with others from Rodhiem-Bieber

* The Joahnn Heinrich Krueckberg family arrived in NYC from Bremen, on 5 Nov 1849. They Weiland family and other families who came on the Orion, on 5 Nv 1849, from Bremen to NYC,
  
  - I belive Johann Heinrich Krueckeberg was a cousin to my 3x great grandfather

  - The Bleekes, of course, came first. And they came from the same general aread around Minden as
    the Weilands. Valhsing.

But other families also came on the same ship together. Wit the Pepplers came Dudenhoefers and Doesnges (and maybe others?), who may have settled in Allen County.
In 1849, the Weiland family and the Johann Heinrich Krueckeberg came together. And<M-F4> others?
In 1850, others came with the the Krueckebergs.

When did the Baade, Wiebke, Harman, etc familes come together?

So there was prior relationships of either marriage, friendship or church fellowship that led several families to travel on the same ship. Later on


* Some of their children mrried on another.

* These familiies settled in the sections of townships and found Lutheran churches together.

* They lived near one another.
  - This was especially true when children married. they often settle next to parents, who may have help:w
ed them obtain land.

* Later were witnesses to Wills or Land Deeds, of one another.

The effort is to notice, document and trace these relationships. Thus discovering a joint family narrative.



