YAML Explained: https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started
insert unkown person
insert father 
fid=get last insert if
insert mother
mid=last isert id 
insert children


person:
   founder:y
   fname:Johann Heinrich Philip
   lname:Bleeke
 father:
     fname: Fridrich
     lname: Bleeke
  mother: 
     fname: Anna Margaretha
     lname: Volkening
  bdord: Leteln
  parish: Windheim
  kreis: Minden
  land: Prussia
  bdate: 3 November 1797
  events: 
   baptized:
     date: November 1797
     pastor: Peikmann 
     godperson: 
       person:
        Johann Fridrich Volkening. He was
   confirmed:
     date: Sunday after Easter, 1810.
   married: 
     date: spring 1819
     wife:
       person: 
         fname: Christine Maria
         lname: Schwier
           father: 
           fname:Christian Fridrich
           lname:Schwier
         mother: 
           fname: Catharina Margareta 
           lanem: Rösner
         bdate: 13 May 1798
         events: baptized in the same month in the
Protestant Lutheran Church in Frülle (Frille) by Pastor Peikmann. Her
godparents are: Anna Sophie Rösner and Christine Müller. She was
confirmed on Sunday after Easter, 1811.

The above mentioned Johann Heinrich Philipp Bleeke emigrated in 1834 to
the United States of North America. His family followed him there within
the following 2 years. After he lived for some time in Wheeling, VA, and
in Cincinati (Cincinnati), Ohio, he moved to this area in 1840. It was
through his efforts and with the help of God that the local Protestant
Lutheran Imanuel Church community formed in 1849.

His children are:

children:
1. Carl Heinrich, born: 27 April, and baptised: 30 April
1818. Godfather: Fridrich Schwier; confirmed on Sunday after Easter,
1832; died on 25 March 1839.

2. Christian Fridrich, born: the 7st of May, and baptized on
13 May 1821. Godfather: Carl Fridrich Bleeke, confirmed on Judica
Sunday, 1835.

3. Carl Fridrich, born: 17 July, and baptised: 20 July 1823.
Godfather: Christian Fridrich Bleeke; died on 11 May 1825.

4. Carl Fridrich Wilhelm, born: 30 November, and baptised: 4
December 1825. Godparents: Fridrich Meier and Christ. Bleeke; confirmed
on Easter 1840 by Pastor Möllmann in Cincinnati.

5. Christine Maria, born: the 11st, and baptised: 17 August
1828. Godparents: Anna Soph. Schwier and Maria Meier; confirmed 1842 by
Pastor Sihler in Ft. Wayne.

6. Christine Sophie Eleonore, born: 13 August, and baptized on
21 August 1831. Godmother: Christine Bleeke; confirmed 1845 by Pastor
Sihler, Ft. Wayne, Ind.

7. Marie Louise Eleonore, born: the 15st, and baptised: 24
November 1833. Godparents: Louise Schwier and Marie Bleeke; confirmed
1848 by Pastor Jäbker in Adams Co., Ind.

8. Emilie, born: 11 March, and baptised: [empty] 1837 in
Cincinati (Cincinnati), Ohion. Baptized by Pastor Lauer. Godmother:
Christine Bleeke; died 8 Sept. 1838, in her birth town of Cincinati
(Cincinnati).

founder: Johann Heinrich Krückeberg

He was born: August 12, 1806 in Behrenbusch (Berenbusch), Principality
Schaumburg-Lippe, and he was baptized in the evangelical Lutheran church
in Petzen by Pastor Stille. His godparents were Gottlieb Krückeberg and
Christian Tägtmeier, and his parents were Jobst Krückeberg and Christine
Eleonore neé Tägtmeier. He was confirmed around Easter 1820 by Pastor
Stille.

He married the maiden Caroline Sophie Weÿland (ÿ will morph in later
years either into Weiland [most common] or Weyland), who was born on
January 23rd 1808, baptized January 29st 1808, and confirmed around
Easter 1822. Her parents are: Fridrich Wilhelm Weÿland and Catharina neé
Hahn. She was born in Evesen, Principality Schaumburg-Lippe. She was
baptized, confirmed, and married by the already mentioned Pastor Stille.

He and his wife had three children which were all born in Germany. 

children:

1. Caroline Philippine Dorathee, born: February 27, 1834, and
baptised: March 9 of the same year. Her Godparents were: Doratha
Weÿland, Philippine Watermann, and Caroline Krückeberg.

2. † Christine Sophie Eleonore, born: August 22 and baptized on
the 28st of the same month 1835. Her godmother is: Christine Bleeke.

3. Philippine Christine, born: June 18, 1837, and baptized on
the 24st of the same month. Her godmother is: Caroline Most.

All three children were baptized and confirmed in the evangelical
Lutheran church in Petzen, but the youngest was confirmed by Pastor
Fritze.

The above named Johann Heinrich Krückeberg emigrated with his family to
the United States of North America on September 13, 1849, and then
settled in the parish here on November 21st of the same year. He also
immediately joined the church community.

founder: Johann Heinrich Wilhelm Carl Grote

parents: Heinrich Grote and Sophie neé Barnekamp. He was born: 4
November 1823 in Jenhorst, parish district of Stolzen (Stolzenau),
Kingdom of Hannover, baptised: 9 November 1823 in the Protestant
Lutheran Church in Nenndorf (Samtgemeinde Nenndorf) by Pastor Müller,
and confirmed around Easter 1837 by Pastor Lindemann.

He emigrated to the United States of North America on 8 Sept. 1849, and
arrive in New York on 20 Nov. of the same year. After he worked for a
while there as well as in Fort Wayne and in Preeple (Preble) Township,
Adams County, Ind., he married here on 11 June 1852 the maiden Caroline
Philippine Dorathea Krückeberg (see previous page, child No. 1). He also
settled here at the same time and soon after joined the parish
community.

Children of this marriage are:

children:
1. Carl Heinrich Christian, born: 26 February 1853, and
baptised: 12 March of the same year. Godparents: Heinrich Krückeberg
and Christian Bleeke.

2. Caroline Christine Sophie, born: 9 April, and baptised: 29
April 1855. Godparents: Caroline Grote, Philippine Krückeberg, Leonore
Bleeke.

3. Caroline Christini, born: 11 September, and baptised: 4
October 1857. Godparents: Christine Krückeberg and Philippine
Schamerloh.

4. Carl Wilhelm Christian, born: 15 September and baptised: 6
October 1860. Godparents: Carl Nürge and Christian Schamerloh. Died on 2
January 1862.

5. Wilhelmine Louise, born: 23 Sept, and baptised: 12 October
1862. Godparents: Wilhelmine Nürge and Wilhelmine Weiland.

6. Wilhelmine Christine, born: 12 March, and baptised: 20
March 1865. Godparents: Wilhelmine Weiland and Caroline Schamerloh.


founder: Conrad Dietrich Ferdinand Reinking

parents: Georg Wilhelm Reinking and Maria Lousie Trachtmann (could be, but
it was written over, letters in blue are confirmed), born in Hävern,
parish of Windheim, district of Petershagen, county of Minden, Kingdom
of Prussia, on 8 January and baptised: 14 January 1827; confirmed
around Easter 1841 by Pastor Köhn. His godparents are Conrad Reinking
and Dietrich Bloome.

He emigrated with his parents to the Unites States of North America on 5
April 1844, and arrived on the 18st of May in New Orleag (New
Orleans?). From there he moved with them to Illinois, and after he lived
there and in St. Louis, MO, for 4 years, he moved to Preeple (Preble)
Township, Adams County, Indiana. In 1853 he settled here and, soon
after, joined the parish community, and married on 26 December 1853 the
maiden Maria Luise Eleonore Bleeke, 7st child of Johann Heinrich
Bleeke and Anna Margaretha neé Volkening (see page 31, child No.7)

Children from this marriage are:

children:
1. Mathilde Christine Louise, born 5 October, and baptized 3
November 1854. Godparents: Christine Bleeke and Louise Reinking.

2. Heinrich Christian Wilhelm, born 18. February, and baptized 2
March 1856. Godparents: Wilhelm Reinking, Johann Heinrich Bleeke, and
Christian Bleeke.

3. Christine Emilie, born 7 March, and baptized 28 March 1858;
died on April 14st of the same year.

4. Christine Maria, born 5 May, and baptized 24 May 1859.
Godparents: Maria Bleeke, and Christine Heckmann.

5. Wilhelmine Christine, born 20. April, and baptized 5 May 1861.
Godparents: Wilhelmine Reinking, Sophie Heckmann and Maria Bleeke.

6. Caroline Christine Elisabeth, born 13 January, and baptized 25
January 1863. Godparents: Caroline Grote and Elisabeth Bibelheimer.

7. Maria Sophia Helena, born 12 September, and baptized 25
September 1864. Godparents: Bernhardine Koldeweÿ (will become Koldewei
or Koldewey), and Maria Carolina Bleeke.

founder: Heinrich Wilhelm Weiland

parents: Fridrich Wilhelm wWeiland and his wife Catharina neé Hahn. He was
born on 14 December 1814 in Evesen, Principality of Schaumburg-Lippe,
and baptised: 19 December 1814 in the Protestant Lutheran Church in
Petzen by Pastor Stille. His godfather was Heinrich Sickmann. He was
confirmed Easter 1828. He married on 15 January 1840 the maiden Sophia
Wilhelmine Piehl, who was born: 11 June 1811, and baptised: 14 June
1811 in the Protestant Lutheran Church in Klein Bremen. Her parents
were: Wilhelm Daniel Piehl and Christine Sophie neé Piehl. She was
confirmed Easter 1825.

He and his wife had 6 children, 3 of which already died in Germany. The
other 3 children that are still alive are:

1. Carl Heinrich Wilhelm, born: 30 July, and baptised: 6
August 1843. His Godparents were: Johann Heinrich Krückeberg and Carl
Piehl.

2. Wilhelmine Christine, born: 5 November and baptised: 15
November 1845. Her Godmother was Louise Dorathea Krückeberg.

3. Christian Fridrich, born: the 12st of January, and
baptised: the 16st of February 1851. His Godparents are Fridrich
Bleeke and Christian Bleeke.

The above named Heinrich Wilhelm Weÿland emigrated with his family to
the Unites States of North America on 13 September 18496. He settled in
the local parish on November 21st of the same year and immediately
joined the parish community.

founder: Johann Andreas Thieme

parents: Johann Andreas Thieme and Johanne Rosine neé. Haugk, born in
Niederfranken (Niederfrankenhain) near Gaitham (Geithain), Kingdom of
Saxonia, on 2 January 1833. He was baptized in the same month at the
Protestant Lutheran Church in Niederfranken (Niederfrankenhein). He was
confirmed in the same church by Pastor Voigt at Michaelmas 1846. His
godparents were Gotthelf Hammer and Fridrich August Haugk.

He emigrated to the United States of North America in August 1855, and
arrived on September 28st of the same year in Fort Wayne, IN. After he
worked there for 4 weeks, he arrived here and, soon after, joined the
parish community.

On 31 Mai 1856, he married the maiden Christine Sophie Eleonore
Krückeberg, the 2nd daughter of Johann Heinrich Krückeberg and
Caroline Sophie neé Weÿland (see page 32, child No. 2).

Children from this marriage are:

children:
1. Johann Fridrich, born: 1 October, and baptised: 10 October
1858. His godparents are: Johann Gottlieb Thieme and Heinrich
Krückeberg.

2. Fridrich Wilhelm, born: 16 July and baptised: 29 July
1860. His godparents are: Wilhelm Weiland and Carl Krückeberg.

3. Caroline Sophie Louise, born: 18 February, and baptised: 2
March 1862. Her godparents are: Caroline Grote and Sophie Thieme.

4. Christine Marie, born: 23 January, and baptised: 7
February 1864. 1863. Her godparents are: Philippine Caroline Schamerloh
and Maria Bleeke.

5. Caroline Philippine, born: 20 October, and baptised: 29
October 1865. Her godparents are: Philippine Weÿland and Philippine
Christine Koldewey.

founder: Carl Fridrich Wilhelm Bleeke

Third son of Johann Heinrich Philipp Bleeke and Christine Marie neé
Schwier. He was born: the 30st of November and baptised: December
4st 1825 (see page 31, child No.4). He married here Maria Bibelheimer,
a daughter of David Daniel Bibelheimer and Maria neé Zähner. She was
born in Wespen Township (West Penn?) Shulkil (Schuylkill) County, PA, on
December 12st 1833, and baptised: January 1st 1834. Godparents:
David Werdmann and his wife Catharina. She was confirmed by Pastor
Fritze on July 28st 1852, and married by the same on December 26st
1853.

Children from this marriage are:

children:
1. Friedrich Wilhelm, born: 13 April, and baptised: 29 April
1855. Godparents: Johann Heinrich Bleeke, Christian Fridrich Bleeke, and
Wilhelm Heckmann.

2. Maria Christine Caroline, born: 4 December, and baptized on
7 December 1856. Godparents: Maria Louise Eleoenore Reinking and
Caroline Scheumann. She died on 18 October 1857.

3. Maria Louise, born: 4 March, and baptised: 28 March 1858.
Godparents: Maria Bibelheimer and Sophie Heckmann.

4. Caroline Elisabeth, born: 1 November, and baptised: 20
November 1859. Godparents: Elisabeth Bibelheimer and Maria Bleeke

5. Christine Emilie, born: 8 September, and baptised: 29
September 1861. Godparents: Christine Maria Heckmann and Caroline
Scheumann.

6. Christian Eduard, born: 5 November, and baptised: 29 Nov.
1863. Godparents: Chr. Fridrich Bleeke, David Daniel Bibelheimer, and
Carl Heckmann.

7. Henriette Helene, born: 29 October, and baptised: 12
November 1865. Godparents: Louise Maria Eleonore Reinking and Henriette
Schnellenberger.


No. ?
founder: Carl Heinrich Wilhelm Krückeberg

parents: Carl Gottlieb Krückeberg and Dorathea neé Weiland. He was born in
Bernbursch (Berenbusch), county of Bückeburg, Principality
Schaumburg-Lippe, on February the 1st 1835 and baptized the same
month. He was confirmed by Pastor Schwertmann on Palm Sunday 1849.

He emigrated with his parents to the United States of North America on
October 1st 1850 and arrived in Fort Wayne, Indiana, on November
26st of the same year*.

He married the maiden Caroline Wilhelmine Kleinschmidt on January 28,
1860. She is a daughter of Christian Kleinschmidt and Sophie. She was
born on September 13, 1834 in Groten-Hirse (now: Großenheerse) county
Petershagen, district Minden, Kingdom of Prussia, and was baptized in
the protestant church in Buchholz by Pastor Köhn. She was confirmed on
Palm Sunday 18(blank) by Pastor Jäbker in Preeble (Preble) Township,
Adams County, Indiana.

Children of this marriage are:

1. Friedrich Christian Wilhelm, born: September 30 and baptized
on October 6, 1860. Godparents: Wilhelm Schamerloh and Christian
Kleinschmidt

2. Sophie Louise, born: July 2 and baptised: July 14 1862.
Godparents: Philippine Schamerloh and Sophie Beeck (or Buuck)

3. Louise Wilhelmine Sophie, born: July 10, 1864, and baptized
on July 17 of the same year. Godparents: Caroline Schamerloh and Emma
Belz

Nr. 9
founder: Carl Dietrich Wilhelm Schamerloh

legitimate son of the landowner Heinrich Christian Schamerloh and his
wife Catharina Margaretha neé Poos, born in Buchholz (Buchholz near
Stadthagen, Schaumburg), Principality of Schaumburg-Lippe, on 31
December 1823, baptised: 11 January 1824, and confirmed on Palm Sunday
1838.

He emigrated to the Unites States of North America on 6 May 1851, and
arrived on the 4st of July of the same year in Fort Wayne, IN.

He married in the local community on 30 April 1857 the maiden Caroline
Philippine Krückeberg, born in Beerenbusch (Berenbusch), Principality of
Schaumburg-Lippe, on October the 15st and baptised: 22 October 1837.
She was confirmed around Easter 1851. She is the legitimate 2nd child
and 1st daughter of Carl Fridrich Krückeberg and his wife Louise
Dorathea neé Weiland.

Children from this marriage are:

(insert in pencil on the side: Carl Wilhelm Christian, see baptismal register Nr. 17) <----

children:
1. Louise Sophie Caroline, born: 10 April, baptised: 15 April
1860. Godparents: Caroline Schamerloh and Caroline Krückeberg.

2. Caroline Wilhelmine, born: 12 January, baptised: 20
January 1862. Godparents: Wilhelmine Weiland and Caroline Grote.

3. Heinrich Wilhelm, born: 19 March, baptized 26 March 1865.
Godparents: Heinrich Krückeberg and Wilhelm Weiland

4. Sophie Wilhelmine, born: 20 October, baptized 31 October
1863. Godparents: Wilhelmine Weiland and Louise Heckmann


founder: Christian Fridrich Bleeke

2nd son of Johann Heinrich Philipp Bleeke and Christine Marie neé
Schwier, born: 7 May and baptised: 13 May 1821 (see page 31, child
No.2). He married 9 August 1849 the maiden Louise Valsing, a daughter of
Friderich Valsing and his wife Ehefrau Louise neé (in pencil:
Kleinschmidt Friedheim), who was born 28 June 1833, and baptized [empty]
August 1833. She was born in Loh (now: Am Loh) county of Minden, Kingdom
of Prussia.

Children from this marriage are:

children:
1. Marie Louise, born 14 November, and baptized 8 December 1850.
Godparents: Wilhelmine Zwick and Sophie Heckmann.

2. Sophie Louise, born 27 March and baptized 28 March 1853.
Godparents: Christine Bleeke, Christine E. Bleeke, and Louise Valsing.

3. Johann Heinrich, born 17 February, and baptized 25 February
1855. Godparents: Johann Heinrich Bleeke and Friedrich Valsing.

In the following year, after a short period of suffering from nervous
fever (usually typhoid fever), the mother of these children went home to
her Lord and was joyfully received by Him. On April 8, 1858, the above
mentioned Chr. Fr. Bleeke married again. He married the maiden Anna
Maria Rup, a daughter of [empty] Rup and [empty]. She was born 11
September 1833, and baptized [empty], in [empty] County, Ohio, and
confirmed [empty]. (note in pencil: died 26 Nov. 1889),

1. Christine Elise, born 1 February, and baptized 27 February
1859. Godparents: Elisabeth Rup and Christine Heckmann; died 6 April
1861.

2. Maria Elise, born 23 June, and baptized 8 July 1860.
Godparents: Maria Reinking and Sahra Rup.

3. Carl Friedrich, born 1 October, and baptized 9 October 1863.
Godparents: Carl Zwick and Carl Heckmann.

4. Friedrich Wilhelm, born 2 October, and baptized 9 October
1863. Godparents: C. Friedrich Wilhelm Bleeke and Ferdinand Reinking.

5. Johannes Martin, born 27 July, and baptized 13 September 1865.
Godparents: Wilhelm Fells and Wilhelm Heckmann.


founder: Carl Heinrich Ludwig Koldeweÿ (will become Koldewei or Koldewey)

Legitimate son of Johann Heinrich Christoph Koldeweÿ and Sophie Mare
Eleonore neé Cordes, born in Hanstedt, Kingdome of Hannover on 31 March
1835, and baptised: 5 April 1835. His godparents are Carl Kemann,
Ludwig Schröder, and Gerhard Schröder. He was confirmed on Palm Sunday
1849.

He emigrated to the Unites States of North America in 1856 where he
arrived on 29 November of the same year. Eventually he moved here and
joined the parish community.

He married on 10 Mai 1861 the maiden Louise Sophie Tiemann, legitimate
daughter of Johann Friedrich Winkelmann and Anna Maria Tiemann. She was
born in Stemshorn, Kingdom of Hannover on 21 October 1841 and was
baptised: 31 October of he same year, and confirmed on Palm Sunday
1855.

Children of this marriage are:

children:
1. Fridrich Heinrich, born: 9 January, and baptised: 19
January 1862. Godparents: Johann Heinrich Bleeke and Fridrich Koldeweÿ.

2. Emma Maria Catharina, born: 23 December, and baptised: 25
December 1863. Godparents: Maria Tiemann and Catharina Koldeweÿ.

3. Louise Maria, born: 22 January, and baptised: 28 January
1866. Godparents: Louise Wittfeld and Maria Thile.


No. ?
founder: Jakob Stöhr

Legitimate son of Fridrich Jakob Stöhr and Margaretha neé Kern, born in
Ronbach Reinbeiern, Kingdom of Bavaria, on 22 March 1830. He was
baptized in the same month. Godfather: Fridrich Stöhr. Confirmed on Palm
Sunday 1843.

He emigrated with his parents to the United States of North America on 4
May 1852, and arrived in Mansfield, Ohio, on 17 July 1852. After he had
lived in the state of Ohio for 6 ½ years, he settled in the area around
here in February 1859, upon which he immediately joined the parish. He
married on 19 January 1857 Elisabeth Mitteldorf, a daughter of Bernhard
Mitteldorf and Gertraud neé Bechhold. She was born in Buchholz, Kingdom
of Prussia, on 22 February 1838, baptized in the same month, and
confirmed [empty]. She emigrated with her parents in 1845 to the United
States of North America.
German Transcript

No. ?

== Christian Dietrich Schamerloh


No. ? (3 or 13?)
founder: Christian Dietrich Schamerloh

legitimate son of the landowner Heinrich Christian Schamerloh and his
wife Catharina Margaretha neé Poos (No. 20), born in Buchholz (Buchholz
near Stadthagen, Schaumburg), Principality of Schaumburg-Lippe, on 15
February 1831, baptised: February the 20st of the same year, and
confirmed on Sunday after Easter 1845

He emigrated to the Unites States of North America on 6 May 1851, and
arrived on the 4st of July of the same year in Fort Wayne, IN.

He married in the local community on 6 May 1859 Caroline Philippine
Sophie Krückeberg, a daughter of Carl Gottlieb Krückeberg and Dorathea
neé Weiland, born in Berenbusch, district of Bückeburg, Principality of
Schaumburg-Lippe, on September the 8st and baptised: 13 September
1840, confirmed on Palm Sunday 1854.

children:

1. Carl Friedrich Wilhelm, born 19 September, and baptized 1
October 1854. Godparents: Carl Dietrich Wilhelm Schamerloh and Carl
Heinrich Wilhelm Krückeberg

†2. Heinrich, born 2. Mai 1861, received emergency baptism, and died 2
days later on the 4st of May 1861.

†3. Caroline Wilhelmine Louise, born 18 March, and baptized 23 March
1862. Godparents: Caroline Philippine Schamerloh and Caroline Wilhelmine
Krückeberg.

4. Heinrich Christian Wilhelm, born 26 September, and baptized 4
October 1863. Godparents: Heinrich Krückeberg and Wilhelm Weiland.

5. Caroline Sophie, born 25 February, received emergency baptism,
and died 2 days later on the 27st of February 1865.

founder: Heinrich Jacob Rücklos (senior)

Legitimate son of [empty] Rücklos and [empty].

He was born in Rumbach, district of Dahn, Rein-Pfalz
(Rhineland-Palatinate), Kingdom of Bavaria, on 16 November 1833, and
baptized in the same month. He was confirmed on Palm Sunday 1847. In the
spring of 1856, he emigrated to the United States of North-America.
After he visited his old homeland once more in 1859 and returned back
here the following year, he married the maiden Friderike Dauer, who was
born in Bergzabern, Kingdom of Bavaria on 17 May 1841, baptized in the
same month of 1841, and confirmed on Palm Sunday 1855. She came to
America in 1860.

Children from this marriage are:

children:
1. Elisabetha, born: 14 July, and baptised: 18 July 1861.
Godparents: [empty]

2. Friedrich Jakob, born: 2 May, and baptised: 16 May 1864.
Godparents [empty]

founder: Heinrich Jacob Rücklos (junior)

Legitimate son of Heinrich Jacob Rücklos and Elisabeth neé Stöhr, born
in Rumbach, district of Dahn, Rein-Pfalz (Rhineland-Palatine), Kingdom
of Bavaria, on 28 January 1842, and baptized the following month.

He emigrated with his parents to the United States of North-America in
May 1852. He married on 16 April 1863 the maiden Anna Elisabeth
Hoffmann, who was born: 12 June 1842 and baptized in the same month.
She was born in Bärweiler, Principality of Hesse-Homburg. Her parents
are Philipp Peter Hoffmann and Maria Elisabeth neé Wendel.

Children from this marriage are:

children:
1. Ludwig Wilhelm, born: 11 January ; baptised: 7 February 1864. Godparents: Johann H. Bleeke and Georg P. Germann.


founder:Abraham Stendler

legitimate son of Jakob Stendler and Maria Elisabeth neé Alexander, was
bon in Klingen, Kanton (district) Bergzabern, in the Kingdom of Bavaria,
on November 22nd 1831. He was baptized in the same month. He was
confirmed in March 1845.

He immigrated in this country in March of 1860. He first worked in Ohio
but then later moved here, were he joined the community (parish) and
married on December 30st 1862 the maiden Maria Belz, a daughter of
Peter Belz and Elisabeth neé Bibelheimer. Maria Belz had been born on
July 2nd 1838 in West Pennsylvania, in Schuylkill County, Pa. She was
confirmed on April 4st 1852.

No.19
founder: Georg Conrad Wilhelm Reinking

parents: Johann Friedrich Conrad Reinking and Maria Elisabeth neé
Engelking, born: 8 July 1796, and baptized in the same month of the
same year. Born in Hävern, parish of Windheim, county of Minden, Kingdom
of Prussia. His godparents were Wilhelm Kaiser and C. Pudelitz. He was
confirmed on the Sunday after Easter in 1810. He was married on 2 July
1821 to Maria Louise Charlotte neé Tragtmann, a daughter of Christian
Tragtmann. She was born: 24 December 1800, and baptized in the same
month.

children:

1. Fridrich Christian, born: 15 December 1821, and baptized in
the same month. Godfather: Fridrich Engelking. He was confirmed on
Sunday after Easter 1835.

2. Conrad Dietrich Ferdinand, born: 8 January, and baptized on
14 January 1827. Godparents: Conrad Reinking and Dietrich Bloome. He was
confirmed on Sunday after Easter 1841.

3. Maria Wilhelmine, born: 6. May 1831, and baptized in the
same month. Godmother: Sophia Reinking. She was confirmed in 1845.

4. Auguste Matilde Dorathee, born: 13 September 1833, and
baptized in the same month. Godmother: Friderike Brockhorn. She was
confirmed around Easter 1847 by Pastor Walther, St. Louis.

5. Conrad Christian Wilhelm, born: 22 July 1839, and baptized
in the same month. Godparents: Conrad Storm and Christian Dietrich
Lessmann. He was confirmed around Easter 1853.

He emigrated with his family to the Unites States of North America on 5
April 1844, where he arrived on the 18st of May in New Orleag (New
Orleans?). From there, he moved to southern Illinois, and, after he
lived there and in St. Louis, MO, for 4 years, he moved to Preeble
(Preble) Township, Adams County, Indiana, where his wife died on August
10st 1850.

In 1854 he moved here to his son and soon joined the parish community.
Besides the five children that are listed above and that are all still
alive, the above mentioned married couple had 1 more son and 4 more
daughters. Of these, the son and three of the daughters died in Germany
while the 4st daughter died in St. Louis, Mo.

founder: David Bibelheimer

legitimate son of [empty] Bibelheimer and [empty] born in West -Penn
Schulkill (Schuylkill) County, PA. on 5 October und baptised: 17
November 1805. Confirmed in 1819. He married on [empty] the maiden Maria
[empty] a daughter of [empty] She was born in the above named place on 9
January and baptised: 1 May 1810. He moved here in 18[empty] and soon
after joined the parish community.

Children of this marriage are:

1. [empty]

2. [empty]

3. [empty]

4. [empty]

5. [empty]

6. Elisabeth, born: 18 December 1841 in Huma, Madina (Medina)
County, OH, and baptised: 20 March 1842. Godparents: Ruben Mansy and
his wife; confirmed on 28 March 1858 by Pastor Jäbker.

7. Harietta, born: 7 February, and baptised: 10 March 1845 in
Medina County, Ohio. Godparents: Johann Miller and his wife Rosine;
confirmed on [empty] by Pastor [empty].

8. Amanda, born: 17 January and baptised: 7 March 1848 in
Medina County, Ohio. Godparents: Johann [empty] and his wife Pennina;
confirmed in July 1865 by Pastor Fritze.

9. Isabella, born: 21 February, and baptised: 1 March 1851.
Godparents: Louise Bleeke and Maria Bleeke.
