. Insert all the persons listed in the biographies.
. Then insert ceremonies, families and children.

== Johann Heinrich Philipp Bleeke

sex:m
fname: Johann Heinrich Philipp
lname: Bleeke 
father: Fridrich Bleeke
mother: Anna Margaretha Volkening
bdate:3 November 1797
is_founder:true
bdorf: Leteln
bdorfb:  Kanton Windheim
bkreis:Kreis Minden
bland:Königreich Preussen


baptism: November 1797
baptism pastor: Peikman
gidparents: Johann Fridrich Volkening
confirmed: Sunday after Easter 1810
married: spring 1819
marriage place: Frühling

wife: Christine Maria Schwier
father: Christian Fridrich Schwier
m: Catharina Margareta Rösner
geb: 13 May 1798
getauft: May 1798
getafut kirche: Frille 
pastor: Peikmann. 
Taufpathen: Anna Sophie Rösner; Christine Müller
confirmiert: Sonntage nach Ostern 1811.


Auswandert: 1834. He first lived for a time in Wheeling Va und in Cincinati (Cincinnati)

Union twp: 1840
Immanuel: helped found it in 1849

children:

1. Carl Heinrich, 
born:  den 27 April u. get. den 30 April 1818.
Taufpathe: Fridrich Schwier, confirmiert am Sonnt. n. Ostern 1832; gest.
den 25 März 1839.

2. Christian Fridrich, 
born:  den 7 Mai und get. den 13 Mai 1821.
Taufpathe: Carl Fridrich Bleeke, confirmiert am Sonnt. Judica 1835.

3. Carl Fridrich, 
born:  den 17 Juli u. get. den 20 Juli 1823.
Taufpathe: Christian Fridrich Bleeke; gestorben den 11 Mai 1825.

4. Carl Fridrich Wilhelm, 
born:  den 30 November u. getauft den 4
December 1825. Taufpathen: Fridrich Meier und Christ. Bleeke;
confirmiert um Ostern 1840 on Past. Möllmann in Cincinati.

5. Christine Maria, 
born:  den 11 u. get. den 17 August 1828.
Pathen: Anna Soph. Schwier und Maria Meier; conf. von Past. Sihler, Ft.
Wayne ‚42

6. Christine Sophie Eleonore, 
born:  den 13 August u. get. den 21
August 1831. Pathen: Christine Bleeke, conf. 1845 von Past. Sihler, Ft.
Wayne, Ind.

7. Marie Louise Eleonore, 
born:  den 15 und get. den 24 November
1833. Pathen: Louise Schwier und Marie Bleeke; conf. 1848 von Past.
Jäbker in Adams Co., Ind.

8. Emilie, 
born:  den 11 März u. get. den [empty] 1837 in Cincinati
(Cincinnati) O. Getauft von Past. Lauer. Pathen: Christine Bleeke,
gestorben den 8 Sept. 1838, in ihrem Geburtsort Cincinati (Cincinnati).
