== Preliminary Resources for Further Peppler Research

https://www.genealogycenter.info/fwacdb.php[Fort Wayne and Allen County Resources] page has a list of many research resources.

==== Genealogy Center Dataabases

A guide to types and sources of newpaper records is Melissa Tennant’s
handout from her ACGS lecture
link:~/g/lectures/newspaper-sites-for-family-historians.pdf[Newspapers
for Family Historian]

Genealogy Center’s list of databases copied from
https://acpl.lib.in.us/explore-genealogy/our-resources[about Our Databses]

Free Databases:

[width="100%",cols="43%,57%",options="header",]
|===
|Database
|Description
|http://www.genealogycenter.info/search_microtext.php[Microtext Catalog]
|The Genealogy Center Microtext Catalog is a searchable listing of microfilm and microfiche available in The Genealogy Center.

|http://www.genealogycenter.info/africanamerican/[African American Gateway]
|The African American Gateway is a growing resource for African
American research, and includes information from the United States,
Canada, and the Caribbean, and well as a few other countries. The links
to websites in this gateway are paired with a bibliography of resources
for African American research in The Genealogy Center collection.

|http://www.genealogycenter.info/fwacdb.php[Allen County, Indiana Resources]
|The Allen County, Indiana Resources collection of databases
includes, but is not limited to indexes of local obituaries, cemeteries,
marriage, death and other courthouse records, as well as
African-American material. Also featured are images from the Firefighter
Collection and local wills.

|http://www.genealogycenter.info/bibles/[Family Bible Records]
|The Family Bible Records section features transcriptions and images from
family bibles donated to The Genealogy Center. Details include births,
marriages, and deaths as well as information from items inserted in the
Bibles, such as newspaper clippings, photographs, and funeral cards.

|http://www.genealogycenter.info/familydb.php[Family Resources]
|The Family Resources section features unique family histories and family
files submitted by researchers who have granted permission for their
material to be hosted on The Genealogy Center site. Contributions of
additional data are most welcome.

|http://www.genealogycenter.info/search_gensurnames.php[Genealogy Center Surname File]
|The Genealogy Center Surname File can be searched to
identify others researching your same surname. Contact information is
provided to encourage collaboration. Contributors to this file are
Genealogy Center patrons.

|http://www.genealogycenter.info/indiana[Indiana Resources]
|Indiana Resources represent a widely varied collection of databases created by
researchers who have donated their work to The Genealogy Center, as well
as Genealogy Center staff. This collection grows rapidly as more
material becomes available.

|http://www.genealogycenter.info/nativeamerican/[Native American Gateway]
|The Native American Gateway is a resource for those exploring
First Nations family history. Information on how to begin such research,
links to materials from the National Archives and links to popular data
are complemented by a continually updated listing of resources held by
The Genealogy Center.

|http://www.genealogycenter.info/otherstates[Other States Resources]
|Other States Resources represent a widely varied collection of
databases created by researchers who have donated their work to The
Genealogy Center, as well as Genealogy Center staff. This collection
grows rapidly as more material becomes available.

|http://www.genealogycenter.info/military/[Our Military Heritage]
|Our Military Heritage includes images of books, pamphlets, government
documents, original letters, diaries, biographies, photographs, videos,
unit histories, and rosters as well as service and pension records. A
project of The Genealogy Center, this collection of data files offers
materials from the Colonial era through the Afghanistan and Iraqi Wars.
Contributions of additional data are most welcome.

|https://www.genealogycenter.info/persi/[Periodical Source Index (PERSI)]
|PERSI is the premier subject index for genealogy and local
history periodicals, and is produced by the staff of The Genealogy
Center. Using this valuable resource provides citations to tens of
thousands of periodicals across North America, the British Isles, and
Europe.

|http://contentdm.acpl.lib.in.us/digital/[Community Album]
|The Allen County Public Library’s Community Album spotlights the history of our
northeast Indiana community as highlighted in photographs, print, and
video. This virtual scrapbook continues to grow with contributions from
the Community.
|===

On-site Databases:

[width="100%",cols="43%,57%",options="header",]
|===
|Database |Description
|https://www.ancestryinstitution.com[Ancestry.com] |Discover your
ancestors at Ancestry.com, the world’s largest family history website.
Browse census records, passenger lists and locality-specific databases
and start your own family tree.

|http://www.accessible-archives.com/collections/african-american-newspapers/[Accessible
Archives African American Newspapers] |Search or browse this unique
collection of 19th century African-American newspapers, including The
Christian Recorder (1861-1891, 1893-1902), The Colored American/Weekly
Advocate (1837-1841), Douglass’ Monthly (1859-1863), Frederick Douglass’
Paper (1851-1855), The Freedmen’s Record (1865-1874), Freedom’s
Journal (1827-1829), The National Era (1847-1860), The Negro Business
League Herald (1909), The North Star (1847-1851), and Provincial
Freeman (1854-1857).

|http://africanamericanheritage.proquest.com/[African American Heritage]
|African American Heritage is an essential collection of databases and
resources for African American research. It includes original records,
the AfriGeneasTM Community social networking site, and Black Genesis, a
state-by-state methodological resource guide.

|http://search.proquest.com/?accountid=8269[African American Historical Newspapers]
|The ``Genealogy'' link leads one to a collection of nine
distinct African-American newspapers, featuring the Atlanta Daily
World (1931-2003), The Baltimore Afro-American (1893-1988), Chicago
Defender (1910-1975), Cleveland Call and Post (1934-1991), Los Angeles
Sentinel (1934-2005), New York Amsterdam News (1922-1993), The Norfolk
Journal and Guide (1921-2003), The Philadelphia Tribune (1912-2001),
and Pittsburgh Courier (1911-2002).

|https://search.ebscohost.com/login.aspx?authtype=ip,cpid&custid=s9069710&groupid=main&profile=ehost&defaultdb=h7i[African American Historical Serials Collection]
|The *African American Historical Serials Collection* is an archive of periodicals that document the
history of African American religious life and culture between 1829 and
1922. It includes newspapers and magazines, plus reports and annuals
from African American religious organizations, including churches and
social service agencies.

|https://infoweb.newsbank.com/signin/AllenCountyPublicLibrary/GBNL[America’s GenealogyBank]
|Search or browse through these database collections of
Historical Newspapers (1690-1922), Historical Books (1749-1900),
Historical Documents (1789-1994), and America’s Obituaries
(1977-current).

|http://www.americanancestors.org/[AmericanAncestors.org]
|AmericanAncestors.org, produced by the New England Historic
Genealogical Society (NEHGS), provides a wealth of resources for
researching New England and early American families. The site includes
many searchable databases, the NEHGS library catalog and publications
list, and more.

|http://www.aihc.amdigital.co.uk/[American Indian Histories and Cultures]
|This collection of manuscripts, rare and original documents
from treaties, speeches and diaries, as well as historic maps and travel
journals dates from the earliest contact with European settlers right up
to photographs and newspapers from the mid-twentieth century.

|http://www.americanindiannewspapers.amdigital.co.uk/[American Indian Newspapers]
|Explore nearly 200 years of Indigenous print journalism
from the United States and Canada. This resource has been developed
with, and has only been made possible by, the permission and
contribution of the newspaper publishers and Tribal Councils concerned.

|http://go.gale.com/gdsc/start.do?p=GDSC&u=fort37223&authCount=1[Archives Unbound: Evangelism in Africa: Correspondence of the Board of Foreign Mission, 1835-1910]
|A unique collection of records of the Board of Foreign Missions of the Presbyterian Church, an agency that created
orphanages, schools, hospitals, and churches in Africa from 1835-1910, is accessible on Archives Unbound.

|http://go.gale.com/gdsc/start.do?p=GDSC&u=fort37223&authCount=1[Archives Unbound: The Civil War in Words and Deeds]
|Archives Unbound is a collection of regimental histories and personal narratives documenting
all facets of military life during the Civil War.

|http://go.galegroup.com/gdsc/i.do?action=interpret&id=5UAJ&v=2.1&u=fort37223&it=aboutCollections&p=GDSC&sw=w&authCount=1[Archives Unbound: The War of 1812: Diplomacy on the High Seas]
|The Archives Unbound: The War of 1812: Diplomacy on the High Seas collection includes
applications from privateers, documents regarding enemy aliens and
prisoners of war, and passenger lists from the United States covering
the time period of 1812-1814.

|https://app.arkivdigital.se/organizations/R4RJnZva7v06YX8wwAV0yNUMhTHQ_FTl[ArkivDigital]
|ArkivDigital is the largest private provider of Swedish church records
and other historical records online. This site includes various kinds of
historical documents such as church records, court records and inventory
of estates.

|https://search.proquest.com/hnpglobeandmail?accountid=8269[Canada’s Heritage from 1844–The Globe and Mail]
|Published in Toronto and covering the years 1844-2009, this historical newspaper archive contains
stories, photographs, birth and marriage announcements, death notices,
and more.

|https://search.ebscohost.com/login.aspx?authtype=ip,cpid&custid=s9069710&groupid=main&profile=ehost&defaultdb=ear[Ebony Magazine Archive]
|The ``Ebony Magazine Archive'' covers civil rights,
education, entrepreneurship and other social topics with an
African-American focus. It includes more than 800 issues providing a
broad view of African-American culture from its first issue in 1945
through 2014.

|http://www.findmypast.com/[FindMyPast]
|One of the best online sources for British research, and increasingly a major resource for North
American records and images, FindMyPast features census schedules, vital
records, church registers, and military records; British, Irish and
American newspapers; and much more. 

|http://www.fold3.com/institution-index.php[Fold3.com]
|At Fold3.com, it is possible to search for or browse millions of historical documents and
photographs. This database includes digital images of military records,
city directories and many other resources. 

|http://www.jewishlife.amdigital.co.uk/[Jewish Life in America]
|This resource explores the history of Jewish communities in America from the
arrival of the first Jews in the 17th century through to the mid-20th
century. This treasure trove of material provides digital images of
collections from the American Jewish Historical Society in New York. In
addition, Jewish Life in America contains interactive maps, essays by
leading scholars, a selection of American Jewish Year Book articles, and
links to other useful websites.

|http://search.ebscohost.com/login.aspx?authtype=ip,cpid&custid=s9069710&site=mhlibed&return=y[MyHeritage]
|The ``MyHeritage Library Edition'' link leads to a searchable database
of more than 9 billion historical records and family trees. The records
range from census, vital records, military, immigration, and much more
covering the United States, Canada, Europe, and more.

|https://infoweb.newsbank.com/signin/AllenCountyPublicLibrary/FWNB[News Sentinel Text Archive]
|Search or browse through The News Sentinel newspaper articles from Fort Wayne, IN for 1962-2019.

|https://access.newspaperarchive.com/[NewspaperArchive]
|Search or browse for your ancestors among newspaper articles available on
NewspaperArchive. This database features newspapers covering all 50
states in the U.S. and 47 other countries from the 1600s to current.

|http://www.newspapers.com/[Newspapers.com]
|Search or browse for your ancestors among newspaper articles on Newspapers.com. This database
features more than 3100 historical newspapers, covering the United
States, Canada, England, Ireland, and Panama from the 1700s-2000s.

|http://infotrac.galegroup.com/itweb/fort37223?db=SAS[Slavery and Anti-Slavery: A Transnational Archive]
|The Slavery and Anti-Slavery database is a rare historical archive of court records, maps, books,
newspapers, and periodicals from the United States, Latin America, the
Caribbean, Africa, and Europe specific to the topics of slavery,
abolition, and emancipation.
|===

==== Uncited Stores about Bender Family in New York and Nebraka

According to a short short accomapnying the FindAGrave https://www.findagrave.com/memorial/63678411/frederick-bender[memorial for Frederick Bender (21 Aug 1837 to 28 May 1918)]:

____

Frederick was the first child born to Johann and Alora Bender in Albany, New York. At the age of 5, Frederick and his parents moved to Fort Wayne, Indiana. He married Anna Marie Fuchshuber and five children were born in Indiana to this union. After two older sons, Martin and Louis, came to Seward County looking for employment, the entire family moved west and settled on land purchased from the Burlington Railroad in 1887. The family at that time consisted of Frederick, Anna, his mother, Alora, and children Elizabeth, Christina, John Frederick, and William. His father and one son had died in Indiana. (Taken from Seward County Nebraska 1982)
____


This Bender family story of their time in New York state is from the FamilySearch page for Johann Friedrich Bender, the https://www.familysearch.org/tree/person/collaborate/LHLT-92L[Collaborate tab]. See **Note** 
from the _Frederik Bender from Bender File, 1978_. I was told by the person who posted it that he beilieved he got it from one of his aunts:

____
Frederick Bender was the son of John Frederick Bender who immigrated from Darmstadt, Hesse, Germany to America in 1836, settling near Albany, New York. A son Frederick was born to them August 21, 1837. His father worked for a time as a teamster to pull the boats through the Erie Canal. Not liking the country, he emigrated westward by covered wagon with his brother John Bender and their families. They traveled on the Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana. They settled here, clearing the trees from the land, built a log cabin until a more substantial house could be built. Three more children were born to the family. The fathers were charter members of the Emmanuel Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this union were born five sons and two daughters. The youngest son George died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska while working on the railroad. They wrote to their father of land available for settlers. Frederick Bender purchased 160 acres of land from the Burlington Railroad for $9.00 an acre in Section 21 southwest of the village of Ruby. Later he sold this to his sons. In July 1887 he purchased 80 acres more for himself in Section 28, southwest of Ruby. In October of that year he moved his family to Nebraska. Coming with him were his wife, his aged mother; daughters Elizabeth and Cristina, sons John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel Lutheran Chruch which was organized Feb 25, 1889, the services being held in the District No 7 school house. He was to purchase three more acres of land in the northwest corner of section 27, one half mile east of his home, which he donated to the Immanuel Congregation for church property. Here a church was built, a parsonage and a plot set aside for a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891, the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May 28, 1918. His son John Frederick would inherit the land. Another 66 acres of land had been purchased across the road from him in Section 21, for his son William and his family. John Frederick, known as Fred, married Martha Eckhardt April 18, 1895. To this union were born five sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife 1959) Of the family, Gerhard Bender is the present owner of the farm. Three of his sisters are still living, one sister and four brothers have passed away.
____


The story of how Friedrich Bender came to Allen county is described in a https://www.familysearch.org/tree/person/collaborate/LBHW-89D[Note]
attached to Eleonore Christine Rühl, Friedrich’s wife. The Note explains:

____
Frederick Bender was the son of John Frederick Bender who immigrated
from Darmstadt, Hesse, Germany to America in 1836, settling near Albany,
New York. A son Frederick was born to them August 21, 1837. His father
worked for a time as a teamster to pull the boats through the Erie
Canal. Not liking the country, he emigrated westward by covered wagon
with his brother John Bender and their families. They traveled on the
Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana.
They settled here, clearing the trees from the land, built a log cabin
until a more substantial house could be built.> Three more children were
born to the family. The fathers were charter members of the Emmanuel
Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace
Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the
farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this
union were born five sons and two daughters. The youngest son George
died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both
are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska
while working on the railroad. They wrote to their father of land
available for settlers. Frederick Bender purchased 160 acres of land
from the Burlington Railroad for $9.00 an acre in Section 21 southwest
of the village of Ruby. Later he sold this to his sons. In July 1887 he
purchased 80 acres more for himself in Section 28, southwest of Ruby. In
October of that year he moved his family to Nebraska. Coming with him
were his wife, his aged mother; daughters Elizabeth and Cristina, sons
John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel
Lutheran Chruch which was organized Feb 25, 1889, the services being
held in the District No 7 school house. He was to purchase three more
acres of land in the northwest corner of section 27, one half mile east
of his home, which he donated to the Immanuel Congregation for church
property. Here a church was built, a parsonage and a plot set aside for
a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891,
the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May
28, 1918. His son John Frederick would inherit the land. Another 66
acres of land had been purchased across the road from him in Section 21,
for his son William and his family. John Frederick, known as Fred,
married Martha Eckhardt April 18, 1895. To this union were born five
sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife
1959) Of the family, Gerhard Bender is the present owner of the farm.
Three of his sisters are still living, one sister and four brothers have
passed away.
____

The FamilySearch Life Sketch for
https://www.familysearch.org/tree/person/details/9ZS9-YFF[Frederick Bender] explains

____
On 20 July 1862, Frederick Bender and Anna Marie Fuchshuber were married
by Rev. Charles Adams at St. Mark’s Lutheran Church, on Thiele Road in
Allen County, Pleasant Township, Indiana, in a log cabin church. Their
youngest son, George, died of diptheria at age 8, as did his grandfather
John Frederick, on November 19, 1871. Both are buried at the Emmanuel
Lutheran Church cemetery, Soest, Indiana. In the 1880s, the two older
Bender sons came west to Seward County, Nebraska, while working for the
railroad. Fred purchased 80 acres southwest of Ruby, and in October 1887
he moved his family to Nebraska. Coming with him was his mother, Alora.
He became a charter member of the Immanuel Lutheran Church, which was
organized 25 February 1889, with services held in the district school
house. He purchased three more acres of land, one half mile east of his
home, which he donated to the Immanuel Congregation. Here they built a
church, a parsonage, and a cemetery plot. Eleonora Bender, his mother,
passed away on 12 December 1891, and she was the first person buried in
the cemetery.
____

The FindAGrave memorial for
https://www.findagrave.com/memorial/63678411/frederick-bender[Frederick Bender Jr] also gives this sketch of his life:

____
Frederick was the first child born to Johann and Alora Bender in Albany,
New York. At the age of 5, Frederick and his parents moved to Fort
Wayne, Indiana. He married Anna Marie Fuchshuber and five children were
born in Indiana to this union. After two older sons, Martin and Louis,
came to Seward County looking for employment, the entire family moved
west and settled on land purchased from the Burlington Railroad in 1887.
The family at that time consisted of Frederick, Anna, his mother, Alora,
and children Elizabeth, Christina, John Frederick, and William. His
father and one son had died in Indiana. (Taken from Seward County
Nebraska 1982)
____

===== Hessische Familienkunde Publication Links

* https://wiki.genealogy.net/Hessische_Familienkunde
* this list of https://wiki.genealogy.net/Hessische_Familienkunde[volumes] of the
Hessische Familienkunde Zeichnung.
* The Genealogy Center has many of the Hessische Familienkunde
https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/1560231?offset=0&qs=1685303869&search_in=code&state=code[volumes]
* The Family Search catalog has entries for
https://www.familysearch.org/search/catalog/results?count=20&query=%2Btitle%3AHessische%20%2Btitle%3AFamilienkunde[them]

Volumes of the Hessicahe Familenkunde are available for purchase:

* http://www.genealogie-zeitschriften.de/hessische-familienkunde/index.php[here]
* https://www.zvab.com/buch-suchen/titel/hessische-familienkunde-heft/zeitschrift-periodikum/[and here]

==== FamilySearch wiki

https://www.familysearch.org/en/wiki/Germany_Emigration_and_Immigration[Germany
Emigration and Immigration]

==== Hessische Heimt Zeitschriften

Hessiche Heimat ist ein
http://www.hessische-heimat.de/hheimat.html[Verband] that has been
publishing its magazine in the 1950s. List
http://www.hessische-heimat.de/hhregister50.htm[here]

Genalogy Center has copies. Call number `943.41 H46h`.

Collections by year, and parts of the year, are available from
abebooks.co.uk. See this 1986 collecion
https://www.abebooks.co.uk/servlet/BookDetailsPL?bi=2736673699&searchurl=kn%3DHessische%2BHeimat%2B1986%26sortby%3D17&cm_sp=snippet-_-srp1-_-title10[36.
Jahrgang 1986 Heft 1 - 4 Komplett] published by Hessische Heimat -
Zeitschrift für Kunst, Kultur und Denkmalpflege.

Is it available directly on the Verbands webpage?

==== Hessische familiengeschichtliche Vereingung

The https://www.hfv-ev.de[Hessische familiengeschichtliche Vereingung (HfV)], Hessian Family History Assocation, was founded in 1921 to (as its `About Us` states):

____
Access to sources such as registry office books and church books is not
always easy. Joint research and the exchange of results make work
easier. For this reason, the Hessian Family History Association (HfV)
was founded in Darmstadt in 1921. It essentially works on the three
former provinces of the old Grand Duchy of Hesse and the People’s State
of Hesse: Starkenburg, Oberhessen and Rheinhessen. In addition, former
areas of the Landgraviate of Hesse-Darmstadt, e.g. B. County of
Lichtenberg (Pirmasens), Hessian hinterland.
____

____
The other two clubs in Hesse were founded almost at the same time as our
club. The Society for Family History in Kurhessen and Waldeck (GFKW) and
the Family History Society for Nassau and Frankfurt (FG/FGNF).
____

____
In recent years, the HfV has been able to greatly expand its range of
services through the support of its members and will continue to work to
help our members with their research.
____

The HfV works to:

[arabic]
. digitize and transcribe church book dupicats records, whose originals
are in the Darmstadt State Archives
. describe the HfV’s holdings–periodicals, family history books, local
literature.

Descriptions of its holdings are maintained at GenWiki’s
https://wiki-genealogy-net.translate.goog/Kategorie:Archiv_der_Hessischen_familiengeschichtlichen_Vereinigung_e.V.?_x_tr_sl=auto&_x_tr_tl=en-US&_x_tr_hl=en-US[Archive
of the Hessian Family History Association]. HfV’s digitzation effort
seeks to:

____
We would like to provide as many of the documents that are important for
our work area as possible in our member area.
____

____
One focus is on the digitization of church book duplicates. The
originals are in the Darmstadt State Archives and we have the
opportunity to scan them in the office. The order of the congregations
is determined by the members. There is information about this in the
monthly newsletter and in the news on the homepage.
____

____
If you are interested, please send an email to the managing director at
it@hfv-ev.de
____

____
Transcription Effort
____

____
Fewer and fewer people can read old manuscripts.
____

____
We have therefore built in the option of typing in the most important
information in fields on each page of the duplicate church records in
the members’ area. On the one hand, it is easier for less experienced
users to understand the entries. On the other hand, you can also search
for entries.
____

____
A few church book duplicates are fully transcribed. Many have little or
no recorded entries.
____

____
Which books you work on is up to you. Here, too, it is possible to work
from home.
____

____
If you have any questions, please email the managing director at
it@hfv-ev.de
____

There is also a https://www.rodheimer-geschichtsverein.de/[Rodheimers
Gesichichts- und Heimatverein webpage]

==== Heimatsverein Rodheim-Bieber

https://www.heimatverein-rodheim-bieber.de[Heimatsverein Rodheim-Bieber]

There is also a

* https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Heimat
Rodheim-Bieber]
* The Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Dorf-und
Familiengeschichte wporking group].
* The Vereins has
https://www.heimatverein-rodheim-bieber.de/hv/literatur/[literatur]
available for purchase.

This is a translation of the Dorf und Familian Geschichte’s web page:

____
Village and family history Responsible: Karl-Heinz Reeh Vetzbergerstr.>
21, 35444 Biebertal, Tel.: 06409/9826 The working group exists since the
foundation of the association in 1995. With Ernst Schmidt a Rodheimer
Urgestein was until at the beginning of of 2004 the leader of this
working group.
____

____
On 26.1.2004 Karl-Heinz Reeh and Heinz Peppler were elected as
successors for Ernst Schmidt. Heinz Peppler passed away in 2014.
____

____
The local history and family researcher known as ``Platte Ernst'' was
responsible for a special exhibition in the local history museum
Rodheim-Bieber in February 2002. Under the title ``The life’s work of
Ernst Schmidt as a local historian and family researcher of Rodheim'' he
made his complete activities accessible in the large room of the local
history museum. All his books and treatises, a lot of picture material
as well as some family trees of Rodheim families (altogether nearly 20)
were shown. In 2011 Ernst Schmidt passed away in his 93rd year.
____

____
50th anniversary of the foundation of the singing club Eintracht Rodheim
on July 05, 1914.
____

____
The working group has taken on the task of researching and documenting
village and family history. This includes recording oral traditions in
writing as well as archiving old pictures and, as far as possible,
describing what has been photographed.
____

____
In order to view documents in archives, which are often written in the
old Kurrent script (Sütterlin), it is a great advantage to be able to
read them.
____

____
The temporary exhibitions in the local history museum are also largely
designed by the working group.
____

____
Not only the history of the village but also historical places outside
the village are researched, such as the old entrenchments, the
Königstuhl, the old shooting ranges, the caves at Dünsberg and near
Bieber, forester’s lodges, mills and the old water chamber to name but a
few.
____

____
Also current documentations belong to it, like photographing buildings
which are to be torn down. People who have time and interest to join us
are always welcome.
____

===== Die Veröffentlichungen des Vereins

I found some of the Rodheim-Bieber Heimatverein’s pdf newsletters online
at https://www.yumpu.com/user/heimatverein.rodheim.bieber.de.

==== Hessen Church Records

* https://helmut-hild-haus.de/index.html[Zentralarchiv der Evangelischen
Kirche in Hessen und Nassau (EKHN)]
+
This
https://helmut-hild-haus.de/index/einzelansicht/news/kirchenbuchportal-weitere-gemeinden-online-1.html[page]
explains its church books are being digitized on made available on
https://archion.de[Archion.de].

Archion’s
https://www.archion.de/en/browse/?no_cache=1&path=40821-623350-623353-855430&cHash=e060d4217d1a59919a330f97efeb7848#https://www.archion.de/en/browse/?no_cache=1&path=40821-564945[EKHN
records] appear organized by *Dekanant*, which translates as
``dearnary''. The ``dean'' seems to have been a sort of regional
Lutheran/Protestant paster responsible for a region.

* The EKHN’s church book finder??
https://www.ekhn-zentralarchiv.findbuch.net/php/main.php?ar_id=3669[search
tool] describes the Dekanat of Gießen and explains when Rodheim became
part of it.

There is also another church archive in the state of Hessen, but its
holding a more specifically regional:

* http://www.archiv-ekkw.de/[Landeskirchliches Archiv der Evangelischen
Kirche von Kurhessen-Waldeck]

==== Zugehörigkeit zu Sankt Johannis Gemeinde

They were members of the Sankt Johannis Gemeinde, just north of Emmanuel
(Soest), on the esat side of Wayne Trace just north day of I-469. They
were a splinter congregation of Emmanuel according it
http://www.emmanuelsoest.org/our-history/[history].

==== Marriage of Ludwig ``Louis'' Peppler to daughter of the Benders from Fellinghausen

Ludwig ``Louis'' married Mary Bender, who was born in Indiana, but whose
parents were from Fellinghausen, Hessen-Darmstadt, very close to
Rodheim-Bieber. Who else was from Fellinghausen–the Felds? Did they all
come in chain-migration?

todo: create a timeline and map of where they lived in old country and
where they lived in Marion twp, allen, Indiana.

==== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thid information is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

There is a Heimatverein in Rodheim-Bieber in which the late Heinz
Peppler was the joint-leader of the Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Village
and family history] working group.

==== FamilySearch Wiki Hesse

https://www.familysearch.org/en/wiki/Hesse_(Hessen),_German_Empire_Genealogy

==== History of the Reformed Churches in Germany

* Britanncia article on
https://www.britannica.com/topic/Presbyterian-churches[Reformed and
Presbyterian churches] discusses Reformed Churches in Germany.
* FamilySearch wiki
https://www.familysearch.org/en/wiki/German_Reformed_Church_in_the_United_States[German
Reformed Churches in the United States]
* FamilySearch wiki
https://www.familysearch.org/en/wiki/Determining_the_Church_Your_Ancestor_Attended[Determing
the Church Your Ancestor Attended]
* United Church of Christ page on
https://www.ucc.org/about-us_short-course_the-german-reformed-church/[The
German Reformed Church]
* https://erhistoricalsociety.org/[Evaneglical and Reformed Historical
Society]

==== Map Gießen

History of https://de.wikipedia.org/wiki/Landkreis_Gie%C3%9Fen[Gießen
Landkreis] and
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hesse_GI.svg/1000px-Hesse_GI.svg.png[map]
of LandKreise von Hessen ## Clues to Investigate

==== FANS strategy ideas:

* Sankt Johannis Gemeinde Mitgleider from Rodheim?
+
Church register and other members, possibly from Rodheinm.

A Fort Wayne obituary for Katherine Elisabeth nee Rühl Bender
(1809-1897) can be found by searching
http://friendsofallencounty.org/search_obits1900.php. Use the date of
03/13/1897 and surname of Bender, and be sure to select the 1837-1899
database (as there are two).

Citation: ``Katherina Bender Obituary'', Fort Wayne Daily Sentinel, 13
March 1897, page 4

=== Hessen Historical Information System

Website for https://www.lagis-hessen.de/en[Hessen Historical Information System] .

The state of Hesse has a very extensive Hessen Historical Information
System with has maps and a
https://www.lagis-hessen.de/en/subjects/index/sn/ol[Historical Gazetteer]. And a lot of other things.

=== Bender Leads

Both Johann ``John'' Bender and his brother, Johann Friedrich, who
emigrated in 1836 (and may have later moved from IN to NE later in
life), were Allen Co pioneers.

John Bender’s Find-a-grave
https://www.findagrave.com/memorial/68838340/johannes-bender[memorial]
contains an image of a newspaper snippet about his funeral that says ``a
pioneer Adams township farmer''. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/68838340/johannes-bender : accessed
13 July 2022), memorial page for Johannes Bender (8 Sep 1808–20 Apr
1886), Find a Grave Memorial ID 68838340, citing Soest Emmanuel Lutheran
Cemetery, Fort Wayne, Allen County, Indiana, USA ; Maintained by JC
(contributor 46984629) .
____

His wife’s memorial alos has newpaper clippings. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/141541158/katharina-bender :
accessed 13 July 2022), memorial page for Katharina Bender (8 Jun
1809–13 Mar 1897), Find a Grave Memorial ID 141541158, citing Soest
Emmanuel Lutheran Cemetery, Fort Wayne, Allen County, Indiana, USA ;
Maintained by MJ (contributor 47177744) .
____

The story of how Friedrich Bender came to Allen county is described in a
https://www.familysearch.org/tree/person/collaborate/LBHW-89D[Note]
attached to Eleonore Christine Rühl, Friedrich’s wife. The Note
explains:

____
Frederick Bender was the son of John Frederick Bender who immigrated
from Darmstadt, Hesse, Germany to America in 1836, settling near Albany,
New York. A son Frederick was born to them August 21, 1837. His father
worked for a time as a teamster to pull the boats through the Erie
Canal. Not liking the country, he emigrated westward by covered wagon
with his brother John Bender and their families. They traveled on the
Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana.
They settled here, clearing the trees from the land, built a log cabin
until a more substantial house could be built. Three more children were
born to the family. The fathers were charter members of the Emmanuel
Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace
Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the
farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this
union were born five sons and two daughters. The youngest son George
died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both
are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska
while working on the railroad. They wrote to their father of land
available for settlers. Frederick Bender purchased 160 acres of land
from the Burlington Railroad for $9.00 an acre in Section 21 southwest
of the village of Ruby. Later he sold this to his sons. In July 1887 he
purchased 80 acres more for himself in Section 28, southwest of Ruby. In
October of that year he moved his family to Nebraska. Coming with him
were his wife, his aged mother; daughters Elizabeth and Cristina, sons
John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel
Lutheran Chruch which was organized Feb 25, 1889, the services being
held in the District No 7 school house. He was to purchase three more
acres of land in the northwest corner of section 27, one half mile east
of his home, which he donated to the Immanuel Congregation for church
property. Here a church was built, a parsonage and a plot set aside for
a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891,
the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May
28, 1918. His son John Frederick would inherit the land. Another 66
acres of land had been purchased across the road from him in Section 21,
for his son William and his family. John Frederick, known as Fred,
married Martha Eckhardt April 18, 1895. To this union were born five
sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife
1959) Of the family, Gerhard Bender is the present owner of the farm.
Three of his sisters are still living, one sister and four brothers have
passed away.
____

* The source of the story may be a local volume on fmily gustirt.
* Soest Emmanuel Church Records
* Adams or Marion Twp Histories
* Land Records

=== German Ahnenforcher und Ahnenforchung Gruppe

==== Familienforschung im Hessischen Landesarchiv

State of Hessen page on
https://landesarchiv.hessen.de/genealogie_einleitung[Familienforschung
im Hessischen Landesarchiv]

==== The Working Group of Family Studies Societies in Hesse

The Working Group of Family Studies Societies in Hesse
https://wiki.genealogy.net/Arbeitsgemeinschaft_der_familienkundlichen_Gesellschaften_in_Hessen[Arbeitsgemeinschaft
derfamilienkundlichen Gesellschaften in Hessen], publishes Hessische
Familienkunde

===== Hessische Familienkunde Publication Links

* https://wiki.genealogy.net/Hessische_Familienkunde
* this list of
https://wiki.genealogy.net/Hessische_Familienkunde[volumes] of the
Hessische Familienkunde Zeichnung.
* The Genealogy Center has many of the Hessische Familienkunde
https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/1560231?offset=0&qs=1685303869&search_in=code&state=code[volumes]
* The Family Search catalog has entries for
https://www.familysearch.org/search/catalog/results?count=20&query=%2Btitle%3AHessische%20%2Btitle%3AFamilienkunde[them]

Volumes of the Hessicahe Familenkunde are available for purchase:

* http://www.genealogie-zeitschriften.de/hessische-familienkunde/index.php[here]
* https://www.zvab.com/buch-suchen/titel/hessische-familienkunde-heft/zeitschrift-periodikum/[and
here]

===== Rodheim Researcher Ernst Schmidt’s Volumes

* ``Die Auswanderer aus dem Kirchspiel Rodheim an der Bieber nach
Nordamerika'', Ernst Schmidt, September 1989, Hessische Familienkunde,
Band 19 Heft 7, pages 317f

It gives the birth, marriages and emigration dates of those who
emigrated to North America from Rodheim and nearby Fellinghausen. It
also mentions other relevant facts.

This article is also an indexed, searchable Ancestry source; however,
Ancestry’s version omits details from the article and only contains only
birth. marriage (and possibly) emigration dates. You can see a screen
print of information from the Ancestry.com version of this source:
link:./images/ancestry-citaion-for-ernst-schmidt-rodheim-volume.png[Ancestry.com
images]

* ``Sie gingen nach Amerika: Die Auswanderer aus dem Kirchspiel Rodheim
an der Bieber'', Schmidt, Ernst, ????. In Hessiche Heimat: Aus Natur und
Geschichte (Giessen), no. 2 (18 Jan. 1986), p. 8; no. 3 (1 Feb. 1986),
p. 12; no. 4 (15 Feb. 1986), p. 16.

This is an Ancestry source.

===== Hessische familiengeschichtliche Vereingung

The https://www.hfv-ev.de[Hessische familiengeschichtliche Vereingung
(HfV)], Hessian Family History Assocation, was founded in 1921 to (as
its ``About Us'' states):

____
Access to sources such as registry office books and church books is not
always easy. Joint research and the exchange of results make work
easier. For this reason, the Hessian Family History Association (HfV)
was founded in Darmstadt in 1921. It essentially works on the three
former provinces of the old Grand Duchy of Hesse and the People’s State
of Hesse: Starkenburg, Oberhessen and Rheinhessen. In addition, former
areas of the Landgraviate of Hesse-Darmstadt, e.g. B. County of
Lichtenberg (Pirmasens), Hessian hinterland.
____

____
The other two clubs in Hesse were founded almost at the same time as our
club. The Society for Family History in Kurhessen and Waldeck (GFKW) and
the Family History Society for Nassau and Frankfurt (FG/FGNF).
____

____
In recent years, the HfV has been able to greatly expand its range of
services through the support of its members and will continue to work to
help our members with their research.
____

The HfV works to:

[arabic]
. digitize and transcribe church book dupicats records, whose originals
are in the Darmstadt State Archives
. describe the HfV’s holdings–periodicals, family history books, local
literature.

Descriptions of its holdings are maintained at GenWiki’s
https://wiki-genealogy-net.translate.goog/Kategorie:Archiv_der_Hessischen_familiengeschichtlichen_Vereinigung_e.V.?_x_tr_sl=auto&_x_tr_tl=en-US&_x_tr_hl=en-US[Archive
of the Hessian Family History Association]. HfV’s digitzation effort
seeks to:

____
We would like to provide as many of the documents that are important for
our work area as possible in our member area.
____

____
One focus is on the digitization of church book duplicates. The
originals are in the Darmstadt State Archives and we have the
opportunity to scan them in the office. The order of the congregations
is determined by the members. There is information about this in the
monthly newsletter and in the news on the homepage.
____

____
If you are interested, please send an email to the managing director at
it@hfv-ev.de
____

____
Transcription Effort
____

____
Fewer and fewer people can read old manuscripts.
____

____
We have therefore built in the option of typing in the most important
information in fields on each page of the duplicate church records in
the members’ area. On the one hand, it is easier for less experienced
users to understand the entries. On the other hand, you can also search
for entries.
____

____
A few church book duplicates are fully transcribed. Many have little or
no recorded entries.
____

____
Which books you work on is up to you. Here, too, it is possible to work
from home.
____

____
If you have any questions, please email the managing director at
it@hfv-ev.de
____

There is also a https://www.rodheimer-geschichtsverein.de/[Rodheimers
Gesichichts- und Heimatverein webpage]

===== Heimatsverein Rodheim-Bieber

There is also a

* https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Heimat
Rodheim-Bieber]
* The Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Dorf-und
Familiengeschichte wporking group].
* The Vereins has
https://www.heimatverein-rodheim-bieber.de/hv/literatur/[literatur]
available for purchase.

This is a translation of the Dorf und Familian Geschichte’s web page:

____
Village and family history Responsible: Karl-Heinz Reeh Vetzbergerstr.
21, 35444 Biebertal, Tel.: 06409/9826 The working group exists since the
foundation of the association in 1995. With Ernst Schmidt a Rodheimer
Urgestein was until at the beginning of of 2004 the leader of this
working group.
____

____
On 26.1.2004 Karl-Heinz Reeh and Heinz Peppler were elected as
successors for Ernst Schmidt. Heinz Peppler passed away in 2014.
____

____
The local history and family researcher known as ``Platte Ernst'' was
responsible for a special exhibition in the local history museum
Rodheim-Bieber in February 2002. Under the title ``The life’s work of
Ernst Schmidt as a local historian and family researcher of Rodheim'' he
made his complete activities accessible in the large room of the local
history museum. All his books and treatises, a lot of picture material
as well as some family trees of Rodheim families (altogether nearly 20)
were shown. In 2011 Ernst Schmidt passed away in his 93rd year.
____

____
50th anniversary of the foundation of the singing club Eintracht Rodheim
on July 05, 1914.
____

____
The working group has taken on the task of researching and documenting
village and family history. This includes recording oral traditions in
writing as well as archiving old pictures and, as far as possible,
describing what has been photographed.
____

____
In order to view documents in archives, which are often written in the
old Kurrent script (Sütterlin), it is a great advantage to be able to
read them.
____

____
The temporary exhibitions in the local history museum are also largely
designed by the working group.
____

____
Not only the history of the village but also historical places outside
the village are researched, such as the old entrenchments, the
Königstuhl, the old shooting ranges, the caves at Dünsberg and near
Bieber, forester’s lodges, mills and the old water chamber to name but a
few.
____

____
Also current documentations belong to it, like photographing buildings
which are to be torn down. People who have time and interest to join us
are always welcome.
____

====== Die Veröffentlichungen des Vereins

I found some of the Rodheim-Bieber Heimatverein’s pdf newsletters online
at https://www.yumpu.com/user/heimatverein.rodheim.bieber.de.

===== Hessen Church Records

* https://helmut-hild-haus.de/index.html[Zentralarchiv der Evangelischen
Kirche in Hessen und Nassau (EKHN)]
+
This
https://helmut-hild-haus.de/index/einzelansicht/news/kirchenbuchportal-weitere-gemeinden-online-1.html[page]
explains its church books are being digitized on made available on
https://archion.de[Archion.de].

Archion’s
https://www.archion.de/en/browse/?no_cache=1&path=40821-623350-623353-855430&cHash=e060d4217d1a59919a330f97efeb7848#https://www.archion.de/en/browse/?no_cache=1&path=40821-564945[EKHN
records] appear organized by *Dekanant*, which translates as
``dearnary''. The ``dean'' seems to have been a sort of regional
Lutheran/Protestant paster responsible for a region.

* The EKHN’s church book finder??
https://www.ekhn-zentralarchiv.findbuch.net/php/main.php?ar_id=3669[search
tool] describes the Dekanat of Gießen and explains when Rodheim became
part of it.

There is also another church archive in the state of Hessen, but its
holding a more specifically regional:

* http://www.archiv-ekkw.de/[Landeskirchliches Archiv der Evangelischen
Kirche von Kurhessen-Waldeck]

===== Zugehörigkeit zu Sankt Johannis Gemeinde

They were members of the Sankt Johannis Gemeinde, just north of Emmanuel
(Soest), on the esat side of Wayne Trace just north day of I-469. They
were a splinter congregation of Emmanuel according it
http://www.emmanuelsoest.org/our-history/[history].

===== Marriage of Ludwig ``Louis'' Peppler to daughter of the Benders from Fellinghausen

Ludwig ``Louis'' married Mary Bender, who was born in Indiana, but whose
parents were from Fellinghausen, Hessen-Darmstadt, very close to
Rodheim-Bieber. Who else was from Fellinghausen–the Felds? Did they all
come in chain-migration?

todo: create a timeline and map of where they lived in old country and
where they lived in Marion twp, allen, Indiana.

===== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thisinformation is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

There is a Heimatverein in Rodheim-Bieber in which the late Heinz
Peppler was the joint-leader of the Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Village
and family history] working group.

===== FamilySearch Wiki Hesse

https://www.familysearch.org/en/wiki/Hesse_(Hessen),_German_Empire_Genealogy

===== History of the Reformed Churches in Germany

* Britanncia article on
https://www.britannica.com/topic/Presbyterian-churches[Reformed and
Presbyterian churches] discusses Reformed Churches in Germany.
* FamilySearch wiki
https://www.familysearch.org/en/wiki/German_Reformed_Church_in_the_United_States[German
Reformed Churches in the United States]
* FamilySearch wiki
https://www.familysearch.org/en/wiki/Determining_the_Church_Your_Ancestor_Attended[Determing
the Church Your Ancestor Attended]
* United Church of Christ page on
https://www.ucc.org/about-us_short-course_the-german-reformed-church/[The
German Reformed Church]
* https://erhistoricalsociety.org/[Evaneglical and Reformed Historical
Society]

===== Map Gießen

History of https://de.wikipedia.org/wiki/Landkreis_Gie%C3%9Fen[Gießen
Landkreis] and
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hesse_GI.svg/1000px-Hesse_GI.svg.png[map]
of LandKreise von Hessen ### Clues to Investigate

FANS strategy ideas:

* Sankt Johannis Gemeinde Mitgleider from Rodheim?
+
Church register and other members, possibly from Rodheinm.
* Any neighbors from Rodheim?
* Newspaper articles about their son who survived. Did his obituary
mention his birth place?
* What about the Peppler Bible?

==== Record Sources

* Sankt Johannis Gemeinde
* Land Records
* Probate
* Rodheim
** https://dekanat-giessen.ekhn.de/gemeinden/rodheim-vetzberg.html
** https://www.biebertal.de/infos-tipps/gemeindedaten/geschichte/geschichte-fellingshausencopy-130copy.html
