== Hessian Resources for Further Research

=== Hessische Familienkunde Publication Links

* https://wiki.genealogy.net/Hessische_Familienkunde
* this list of https://wiki.genealogy.net/Hessische_Familienkunde[volumes] of the Hessische Familienkunde Zeichnung.
* The Genealogy Center has many of the Hessische Familienkunde https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/1560231?offset=0&qs=1685303869&search_in=code&state=code[volumes]
* The Family Search catalog has entries for https://www.familysearch.org/search/catalog/results?count=20&query=%2Btitle%3AHessische%20%2Btitle%3AFamilienkunde[them]

Volumes of the Hessicahe Familenkunde are available for purchase:

* http://www.genealogie-zeitschriften.de/hessische-familienkunde/index.php[here]
* https://www.zvab.com/buch-suchen/titel/hessische-familienkunde-heft/zeitschrift-periodikum/[and here]

=== Hessische Heimt (Zeitschriften)

Hessiche Heimat ist ein http://www.hessische-heimat.de/hheimat.html[Verband], der seit 1950s einen Zeitschriten veröffentlichtet.
Eine Liste von alle Aufgaben ist verfügbar http://www.hessische-heimat.de/hhregister50.htm[hier].

Genalogy Center hat die auch. Call number https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/1550371?offset=0&qs=Hessische%20Heimat&search_in=iets&state=search[943.41 H46h]

Collections by year, and parts of the year, are available from abebooks.co.uk, z.B. von die 1986 Versammlung:
link:https://www.abebooks.co.uk/servlet/BookDetailsPL?bi=2736673699&searchurl=kn%3DHessische%2BHeimat%2B1986%26sortby%3D17&cm_sp=snippet-_-srp1-_-title10[36. Jahrgang 1986 Heft 1-4 Komplett] 
Zeitschrift für Kunst, Kultur und Denkmalpflege.

Sind die Aufgaben auf die Webseit von Hessiche Heimat auch verfügbar?

=== Hessische familiengeschichtliche Vereingung

Die https://www.hfv-ev.de[Hessische familiengeschichtliche Vereingung (HfV)] (Hessian Family History Assocation) wurde 1921 gegründet. `About Us` erzählt ihre Zeile:

____
Access to sources such as registry office books and church books is not always easy. Joint research and the exchange of results make work
easier. For this reason, the Hessian Family History Association (HfV) was founded in Darmstadt in 1921. It essentially works on the three
former provinces of the old Grand Duchy of Hesse and the People’s State of Hesse: Starkenburg, Oberhessen and Rheinhessen. In addition, former
areas of the Landgraviate of Hesse-Darmstadt, e.g. B. County of Lichtenberg (Pirmasens), Hessian hinterland.
____

____
The other two clubs in Hesse were founded almost at the same time as our club. The Society for Family History in Kurhessen and Waldeck (GFKW) and
the Family History Society for Nassau and Frankfurt (FG/FGNF).
____

____
In recent years, the HfV has been able to greatly expand its range of services through the support of its members and will continue to work to
help our members with their research.
____

Die HfV arbeitet an die folgenden Aufgaben:

[arabic]
. digitize and transcribe church book dupicats records, whose originals are in the Darmstadt State Archives
	. describe the HfV’s holdings:–periodicals, family history books, local literature.

Descriptions of its holdings are maintained at GenWiki’s
https://wiki-genealogy-net.translate.goog/Kategorie:Archiv_der_Hessischen_familiengeschichtlichen_Vereinigung_e.V.?_x_tr_sl=auto&_x_tr_tl=en-US&_x_tr_hl=en-US[Archive
of the Hessian Family History Association]. HfV’s digitzation effort
seeks to:

____
We would like to provide as many of the documents that are important for our work area as possible in our member area.
____

____
One focus is on the digitization of church book duplicates. The originals are in the Darmstadt State Archives and we have the
opportunity to scan them in the office. The order of the congregations is determined by the members. There is information about this in the
monthly newsletter and in the news on the homepage.
____

____
If you are interested, please send an email to the managing director at
it@hfv-ev.de
____

____
Transcription Effort
____

____
Fewer and fewer people can read old manuscripts.
____

____
We have therefore built in the option of typing in the most important information in fields on each page of the duplicate church records in
the members’ area. On the one hand, it is easier for less experienced users to understand the entries. On the other hand, you can also search
for entries.
____

____
A few church book duplicates are fully transcribed. Many have little or no recorded entries.
____

____
Which books you work on is up to you. Here, too, it is possible to work from home.
____

____
If you have any questions, please email the managing director at it@hfv-ev.de
____

There is also a https://www.rodheimer-geschichtsverein.de/[Rodheimers Gesichichts- und Heimatverein webpage]

==== Heimatsverein Rodheim-Bieber

Der https://www.heimatverein-rodheim-bieber.de[Heimatsverein Rodheim-Bieber] hat einen https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Arbeitskreis Dorf- und Familiengeschichte],
deren https://www.heimatverein-rodheim-bieber.de/hv/literatur/[Literatur] vorhanden ist. Irgendeine der interessantsten Veröffentlichten, die vorhanden ist, sind:

* Ortschronik–Rodheim
* "Rodheim a.d. (an der) Bieber", 2006, von Ernst Schmidt
* "Rodheim Kirche und Friedhof", 2005
* Geschichte Rodheim, 2015
* Ehemalige Geschäfte in Rodheim – Bieber, 2017
* Dreißigjähriger Krieg im Gleiberger Land, 2018
* Siebenjähriger Krieg im Gleiberger Land 2018

This is a translation of the Dorf und Familian Geschichte’s web page:

____
Village and family history Responsible: Karl-Heinz Reeh Vetzbergerstr.  21, 35444 Biebertal, Tel.: 06409/9826
The working group exists since the foundation of the association in 1995. With Ernst Schmidt a Rodheimer
Urgestein was until at the beginning of of 2004 the leader of this working group.
____

____
On 26 January 2004 Karl-Heinz Reeh and Heinz Peppler were elected as successors to Ernst Schmidt. Heinz Peppler passed away in 2014.
____

____
The local history and family researcher known as ``Platte Ernst'' was responsible for a special exhibition in the local history museum
Rodheim-Bieber in February 2002. Under the title ``The life’s work of Ernst Schmidt as a local historian and family researcher of Rodheim'' he
made his complete activities accessible in the large room of the local history museum. All his books and treatises, a lot of picture material
as well as some family trees of Rodheim families (altogether nearly 20) were shown. In 2011 Ernst Schmidt passed away in his 93rd year.
____

____
50th anniversary of the foundation of the singing club Eintracht Rodheim on July 05, 1914.
____

____
The working group has taken on the task of researching and documenting village and family history. This includes recording oral traditions in
writing as well as archiving old pictures and, as far as possible, describing what has been photographed.
____

____
In order to view documents in archives, which are often written in the old Kurrent script (Sütterlin), it is a great advantage to be able to
read them.
____

____
The temporary exhibitions in the local history museum are also largely designed by the working group.
____

____
Not only the history of the village but also historical places outside the village are researched, such as the old entrenchments, the
Königstuhl, the old shooting ranges, the caves at Dünsberg and near Bieber, forester’s lodges, mills and the old water chamber to name but a
few.
____

____
Also current documentations belong to it, like photographing buildings which are to be torn down. People who have time and interest to join us
are always welcome.
____

===== Die Veröffentlichungen des Vereins

I found some of the Rodheim-Bieber Heimatverein’s pdf newsletters online at https://www.yumpu.com/user/heimatverein.rodheim.bieber.de.

==== Hessen Church Records

* https://helmut-hild-haus.de/index.html[Zentralarchiv der Evangelischen Kirche in Hessen und Nassau (EKHN)]
+ This https://helmut-hild-haus.de/index/einzelansicht/news/kirchenbuchportal-weitere-gemeinden-online-1.html[page]
explains its church books are being digitized on made available on https://archion.de[Archion.de].

Archion’s
https://www.archion.de/en/browse/?no_cache=1&path=40821-623350-623353-855430&cHash=e060d4217d1a59919a330f97efeb7848#https://www.archion.de/en/browse/?no_cache=1&path=40821-564945[EKHN
records] appear organized by *Dekanant*, which translates as ``dearnary''. The ``dean'' seems to have been a sort of regional Lutheran/Protestant paster responsible for a region.

* The EKHN’s church book finder??  https://www.ekhn-zentralarchiv.findbuch.net/php/main.php?ar_id=3669[search tool] describes the Dekanat of Gießen and explains when Rodheim became
part of it.

There is also another church archive in the state of Hessen, but its holding a more specifically regional:

* http://www.archiv-ekkw.de/[Landeskirchliches Archiv der Evangelischen Kirche von Kurhessen-Waldeck]

==== Zugehörigkeit zu Sankt Johannis Gemeinde

They were members of the Sankt Johannis Gemeinde, just north of Emmanuel
(Soest), on the esat side of Wayne Trace just north day of I-469. They
were a splinter congregation of Emmanuel according it
http://www.emmanuelsoest.org/our-history/[history].

==== Marriage of Ludwig ``Louis'' Peppler to daughter of the Benders from Fellinghausen

Ludwig ``Louis'' married Mary Bender, who was born in Indiana, but whose
parents were from Fellinghausen, Hessen-Darmstadt, very close to
Rodheim-Bieber. Who else was from Fellinghausen–the Felds? Did they all
come in chain-migration?

todo: create a timeline and map of where they lived in old country and
where they lived in Marion twp, allen, Indiana.

==== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thid information is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

There is a Heimatverein in Rodheim-Bieber in which the late Heinz
Peppler was the joint-leader of the Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Village
and family history] working group.

==== FamilySearch Wiki Hesse

https://www.familysearch.org/en/wiki/Hesse_(Hessen),_German_Empire_Genealogy

==== History of the Reformed Churches in Germany

* Britanncia article on https://www.britannica.com/topic/Presbyterian-churches[Reformed and Presbyterian churches] discusses Reformed Churches in Germany.
* FamilySearch wiki https://www.familysearch.org/en/wiki/German_Reformed_Church_in_the_United_States[German Reformed Churches in the United States]
* FamilySearch wiki https://www.familysearch.org/en/wiki/Determining_the_Church_Your_Ancestor_Attended[Determing the Church Your Ancestor Attended]
* United Church of Christ page on https://www.ucc.org/about-us_short-course_the-german-reformed-church/[The German Reformed Church]
* https://erhistoricalsociety.org/[Evaneglical and Reformed Historical Society]

==== Map Gießen

History of https://de.wikipedia.org/wiki/Landkreis_Gie%C3%9Fen[Gießen Landkreis] and
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hesse_GI.svg/1000px-Hesse_GI.svg.png[map] of LandKreise von Hessen ## Clues to Investigate

=== Hessen Historical Information System

Website for https://www.lagis-hessen.de/en[Hessen Historical Information System] .

The state of Hesse has a very extensive Hessen Historical Information
System with has maps and a
https://www.lagis-hessen.de/en/subjects/index/sn/ol[Historical Gazetteer]. And a lot of other things.

=== Bender Leads

Both Johann ``John'' Bender and his brother, Johann Friedrich, who
emigrated in 1836 (and may have later moved from IN to NE later in
life), were Allen Co pioneers.

John Bender’s Find-a-grave
https://www.findagrave.com/memorial/68838340/johannes-bender[memorial]
contains an image of a newspaper snippet about his funeral that says ``a
pioneer Adams township farmer''. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/68838340/johannes-bender : accessed
13 July 2022), memorial page for Johannes Bender (8 Sep 1808–20 Apr
1886), Find a Grave Memorial ID 68838340, citing Soest Emmanuel Lutheran
Cemetery, Fort Wayne, Allen County, Indiana, USA ; Maintained by JC
(contributor 46984629) .
____

His wife’s memorial alos has newpaper clippings. Citation:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/141541158/katharina-bender :
accessed 13 July 2022), memorial page for Katharina Bender (8 Jun
1809–13 Mar 1897), Find a Grave Memorial ID 141541158, citing Soest
Emmanuel Lutheran Cemetery, Fort Wayne, Allen County, Indiana, USA ;
Maintained by MJ (contributor 47177744) .
____

The story of how Friedrich Bender came to Allen county is described in a
https://www.familysearch.org/tree/person/collaborate/LBHW-89D[Note]
attached to Eleonore Christine Rühl, Friedrich’s wife. The Note
explains:

____
Frederick Bender was the son of John Frederick Bender who immigrated
from Darmstadt, Hesse, Germany to America in 1836, settling near Albany,
New York. A son Frederick was born to them August 21, 1837. His father
worked for a time as a teamster to pull the boats through the Erie
Canal. Not liking the country, he emigrated westward by covered wagon
with his brother John Bender and their families. They traveled on the
Wayne Trace Road coming to the Soest Community near Fort Wayne, Indiana.
They settled here, clearing the trees from the land, built a log cabin
until a more substantial house could be built. Three more children were
born to the family. The fathers were charter members of the Emmanuel
Lutheran Church which was organized Dec 25, 1845 at Soest on the Trace
Road, which today is Southwest of Fort Wayne, in Allen County.
____

____
Here young Frederick grew to manhood helping his father with the
farming. He was to marry Anna Marie Fuchshuber July 20, 1862. To this
union were born five sons and two daughters. The youngest son George
died of Diptheria at age 8 and the father also on Nov. 19, 1871. Both
are buried on Emmanuel Cemetery, Soest.
____

____
In the 1880s, the two older sons came west to Seward County, Nebraska
while working on the railroad. They wrote to their father of land
available for settlers. Frederick Bender purchased 160 acres of land
from the Burlington Railroad for $9.00 an acre in Section 21 southwest
of the village of Ruby. Later he sold this to his sons. In July 1887 he
purchased 80 acres more for himself in Section 28, southwest of Ruby. In
October of that year he moved his family to Nebraska. Coming with him
were his wife, his aged mother; daughters Elizabeth and Cristina, sons
John Frederick age 15, and William age 13.
____

____
He was engaged in farming, became a charter member of the Immanuel
Lutheran Chruch which was organized Feb 25, 1889, the services being
held in the District No 7 school house. He was to purchase three more
acres of land in the northwest corner of section 27, one half mile east
of his home, which he donated to the Immanuel Congregation for church
property. Here a church was built, a parsonage and a plot set aside for
a cemetery. Eleanora Bender, his mother, passed away on Dec 12, 1891,
the first burial on the cemetery. She was 88 years of age.
____

____
Frederick Bender farmed here for the rest of his life, passing away May
28, 1918. His son John Frederick would inherit the land. Another 66
acres of land had been purchased across the road from him in Section 21,
for his son William and his family. John Frederick, known as Fred,
married Martha Eckhardt April 18, 1895. To this union were born five
sons and four daughters. Fred Bender passed away Nov. 11, 1963. (wife
1959) Of the family, Gerhard Bender is the present owner of the farm.
Three of his sisters are still living, one sister and four brothers have
passed away.
____

* The source of the story may be a local volume on fmily gustirt.
* Soest Emmanuel Church Records
* Adams or Marion Twp Histories
* Land Records

=== German Ahnenforcher und Ahnenforchung Gruppe

==== Familienforschung im Hessischen Landesarchiv

State of Hessen page on
https://landesarchiv.hessen.de/genealogie_einleitung[Familienforschung
im Hessischen Landesarchiv]

==== The Working Group of Family Studies Societies in Hesse

The Working Group of Family Studies Societies in Hesse
https://wiki.genealogy.net/Arbeitsgemeinschaft_der_familienkundlichen_Gesellschaften_in_Hessen[Arbeitsgemeinschaft
derfamilienkundlichen Gesellschaften in Hessen], publishes Hessische
Familienkunde

===== Hessische Familienkunde Publication Links

* https://wiki.genealogy.net/Hessische_Familienkunde
* this list of
https://wiki.genealogy.net/Hessische_Familienkunde[volumes] of the
Hessische Familienkunde Zeichnung.
* The Genealogy Center has many of the Hessische Familienkunde
https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/1560231?offset=0&qs=1685303869&search_in=code&state=code[volumes]
* The Family Search catalog has entries for
https://www.familysearch.org/search/catalog/results?count=20&query=%2Btitle%3AHessische%20%2Btitle%3AFamilienkunde[them]

Volumes of the Hessicahe Familenkunde are available for purchase:

* http://www.genealogie-zeitschriften.de/hessische-familienkunde/index.php[here]
* https://www.zvab.com/buch-suchen/titel/hessische-familienkunde-heft/zeitschrift-periodikum/[and
here]

===== Rodheim Researcher Ernst Schmidt’s Volumes

* ``Die Auswanderer aus dem Kirchspiel Rodheim an der Bieber nach
Nordamerika'', Ernst Schmidt, September 1989, Hessische Familienkunde,
Band 19 Heft 7, pages 317f

It gives the birth, marriages and emigration dates of those who
emigrated to North America from Rodheim and nearby Fellinghausen. It
also mentions other relevant facts.

This article is also an indexed, searchable Ancestry source; however,
Ancestry’s version omits details from the article and only contains only
birth. marriage (and possibly) emigration dates. You can see a screen
print of information from the Ancestry.com version of this source:
link:./images/ancestry-citaion-for-ernst-schmidt-rodheim-volume.png[Ancestry.com images]

* ``Sie gingen nach Amerika: Die Auswanderer aus dem Kirchspiel Rodheim
an der Bieber'', Schmidt, Ernst, ????. In Hessiche Heimat: Aus Natur und
Geschichte (Giessen), no. 2 (18 Jan. 1986), p. 8; no. 3 (1 Feb. 1986),
p. 12; no. 4 (15 Feb. 1986), p. 16.

This is an Ancestry source.

===== Hessische familiengeschichtliche Vereingung

The https://www.hfv-ev.de[Hessische familiengeschichtliche Vereingung (HfV)],
Hessian Family History Assocation, was founded in 1921 to (as
its ``About Us'' states):

____
Access to sources such as registry office books and church books is not
always easy. Joint research and the exchange of results make work
easier. For this reason, the Hessian Family History Association (HfV)
was founded in Darmstadt in 1921. It essentially works on the three
former provinces of the old Grand Duchy of Hesse and the People’s State
of Hesse: Starkenburg, Oberhessen and Rheinhessen. In addition, former
areas of the Landgraviate of Hesse-Darmstadt, e.g. B. County of
Lichtenberg (Pirmasens), Hessian hinterland.
____

____
The other two clubs in Hesse were founded almost at the same time as our
club. The Society for Family History in Kurhessen and Waldeck (GFKW) and
the Family History Society for Nassau and Frankfurt (FG/FGNF).
____

____
In recent years, the HfV has been able to greatly expand its range of
services through the support of its members and will continue to work to
help our members with their research.
____

The HfV works to:

[arabic]
. digitize and transcribe church book dupicats records, whose originals
are in the Darmstadt State Archives
. describe the HfV’s holdings–periodicals, family history books, local
literature.

Descriptions of its holdings are maintained at GenWiki’s
https://wiki-genealogy-net.translate.goog/Kategorie:Archiv_der_Hessischen_familiengeschichtlichen_Vereinigung_e.V.?_x_tr_sl=auto&_x_tr_tl=en-US&_x_tr_hl=en-US[Archive
of the Hessian Family History Association]. HfV’s digitzation effort
seeks to:

____
We would like to provide as many of the documents that are important for
our work area as possible in our member area.
____

____
One focus is on the digitization of church book duplicates. The
originals are in the Darmstadt State Archives and we have the
opportunity to scan them in the office. The order of the congregations
is determined by the members. There is information about this in the
monthly newsletter and in the news on the homepage.
____

____
If you are interested, please send an email to the managing director at
it@hfv-ev.de
____

____
Transcription Effort
____

____
Fewer and fewer people can read old manuscripts.
____

____
We have therefore built in the option of typing in the most important
information in fields on each page of the duplicate church records in
the members’ area. On the one hand, it is easier for less experienced
users to understand the entries. On the other hand, you can also search
for entries.
____

____
A few church book duplicates are fully transcribed. Many have little or
no recorded entries.
____

____
Which books you work on is up to you. Here, too, it is possible to work
from home.
____

____
If you have any questions, please email the managing director at
it@hfv-ev.de
____

There is also a https://www.rodheimer-geschichtsverein.de/[Rodheimers
Gesichichts- und Heimatverein webpage]

===== Heimatsverein Rodheim-Bieber

There is also a

* https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Heimat
Rodheim-Bieber]
* The Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Dorf-und
Familiengeschichte wporking group].
* The Vereins has
https://www.heimatverein-rodheim-bieber.de/hv/literatur/[literatur]
available for purchase.

This is a translation of the Dorf und Familian Geschichte’s web page:

____
Village and family history Responsible: Karl-Heinz Reeh Vetzbergerstr.
21, 35444 Biebertal, Tel.: 06409/9826 The working group exists since the
foundation of the association in 1995. With Ernst Schmidt a Rodheimer
Urgestein was until at the beginning of of 2004 the leader of this
working group.
____

____
On 26.1.2004 Karl-Heinz Reeh and Heinz Peppler were elected as
successors for Ernst Schmidt. Heinz Peppler passed away in 2014.
____

____
The local history and family researcher known as ``Platte Ernst'' was
responsible for a special exhibition in the local history museum
Rodheim-Bieber in February 2002. Under the title ``The life’s work of
Ernst Schmidt as a local historian and family researcher of Rodheim'' he
made his complete activities accessible in the large room of the local
history museum. All his books and treatises, a lot of picture material
as well as some family trees of Rodheim families (altogether nearly 20)
were shown. In 2011 Ernst Schmidt passed away in his 93rd year.
____

____
50th anniversary of the foundation of the singing club Eintracht Rodheim
on July 05, 1914.
____

____
The working group has taken on the task of researching and documenting
village and family history. This includes recording oral traditions in
writing as well as archiving old pictures and, as far as possible,
describing what has been photographed.
____

____
In order to view documents in archives, which are often written in the
old Kurrent script (Sütterlin), it is a great advantage to be able to
read them.
____

____
The temporary exhibitions in the local history museum are also largely
designed by the working group.
____

____
Not only the history of the village but also historical places outside
the village are researched, such as the old entrenchments, the
Königstuhl, the old shooting ranges, the caves at Dünsberg and near
Bieber, forester’s lodges, mills and the old water chamber to name but a
few.
____

____
Also current documentations belong to it, like photographing buildings
which are to be torn down. People who have time and interest to join us
are always welcome.
____

====== Die Veröffentlichungen des Vereins

I found some of the Rodheim-Bieber Heimatverein’s pdf newsletters online
at https://www.yumpu.com/user/heimatverein.rodheim.bieber.de.

===== Hessen Church Records

* https://helmut-hild-haus.de/index.html[Zentralarchiv der Evangelischen
Kirche in Hessen und Nassau (EKHN)]
+
This
https://helmut-hild-haus.de/index/einzelansicht/news/kirchenbuchportal-weitere-gemeinden-online-1.html[page]
explains its church books are being digitized on made available on
https://archion.de[Archion.de].

Archion’s
https://www.archion.de/en/browse/?no_cache=1&path=40821-623350-623353-855430&cHash=e060d4217d1a59919a330f97efeb7848#https://www.archion.de/en/browse/?no_cache=1&path=40821-564945[EKHN
records] appear organized by *Dekanant*, which translates as
``dearnary''. The ``dean'' seems to have been a sort of regional
Lutheran/Protestant paster responsible for a region.

* The EKHN’s church book finder??
https://www.ekhn-zentralarchiv.findbuch.net/php/main.php?ar_id=3669[search
tool] describes the Dekanat of Gießen and explains when Rodheim became
part of it.

There is also another church archive in the state of Hessen, but its
holding a more specifically regional:

* http://www.archiv-ekkw.de/[Landeskirchliches Archiv der Evangelischen
Kirche von Kurhessen-Waldeck]

===== Zugehörigkeit zu Sankt Johannis Gemeinde

They were members of the Sankt Johannis Gemeinde, just north of Emmanuel
(Soest), on the esat side of Wayne Trace just north day of I-469. They
were a splinter congregation of Emmanuel according it
http://www.emmanuelsoest.org/our-history/[history].

===== Marriage of Ludwig ``Louis'' Peppler to daughter of the Benders from Fellinghausen

Ludwig ``Louis'' married Mary Bender, who was born in Indiana, but whose
parents were from Fellinghausen, Hessen-Darmstadt, very close to
Rodheim-Bieber. Who else was from Fellinghausen–the Felds? Did they all
come in chain-migration?

todo: create a timeline and map of where they lived in old country and
where they lived in Marion twp, allen, Indiana.

===== FindAGrave Parentage Information for Joh. Jacob Pppler

The Find-A-Grave page for
https://www.findagrave.com/memorial/78479111/pep[Johann Jacob Pppler]
give his parentage:

____
Son of Johann Ludwig Peppler and Katharina Margarethe Meissner Peppler.
Husband of Maria Magdalene Platt Peppler
____

____
Gravesite Details
____

____
Johan was born in Rodheim near Grodrigun, Germany.
____

but the source of thisinformation is not mentioned.

Citation for Johann Jacob Peppler:

____
Find a Grave, database and images
(https://www.findagrave.com/memorial/78479111/johan-jacob-peppler :
accessed 06 July 2022), memorial page for Johan Jacob Peppler (21 Nov
1810–25 Apr 1873), Find a Grave Memorial ID 78479111, citing Saint John
Evangelical Lutheran Church Cemetery, Marion Township, Allen County,
Indiana, USA ; Maintained by Annis Jean Hite Patee (contributor
46907132).
____

There is a Heimatverein in Rodheim-Bieber in which the late Heinz
Peppler was the joint-leader of the Verein’s
https://www.heimatverein-rodheim-bieber.de/hv/arbeitskreise/dorf-und-familiengeschichte/[Village
and family history] working group.

===== FamilySearch Wiki Hesse

https://www.familysearch.org/en/wiki/Hesse_(Hessen),_German_Empire_Genealogy

===== History of the Reformed Churches in Germany

* Britanncia article on https://www.britannica.com/topic/Presbyterian-churches[Reformed and Presbyterian churches] discusses Reformed Churches in Germany.
* FamilySearch wiki https://www.familysearch.org/en/wiki/German_Reformed_Church_in_the_United_States[German Reformed Churches in the United States]
* FamilySearch wiki https://www.familysearch.org/en/wiki/Determining_the_Church_Your_Ancestor_Attended[Determing the Church Your Ancestor Attended]
* United Church of Christ page on https://www.ucc.org/about-us_short-course_the-german-reformed-church/[The German Reformed Church]
* https://erhistoricalsociety.org/[Evaneglical and Reformed Historical Society]

===== Map Gießen

History of https://de.wikipedia.org/wiki/Landkreis_Gie%C3%9Fen[Gießen Landkreis] and
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hesse_GI.svg/1000px-Hesse_GI.svg.png[map] of LandKreise von Hessen ### Clues to Investigate

FANS strategy ideas:

* Sankt Johannis Gemeinde Mitgleider from Rodheim?
+
Church register and other members, possibly from Rodheinm.
* Any neighbors from Rodheim?
* Newspaper articles about their son who survived. Did his obituary
mention his birth place?
* What about the Peppler Bible?

==== Record Sources

* Sankt Johannis Gemeinde
* Land Records
* Probate
* Rodheim
** https://dekanat-giessen.ekhn.de/gemeinden/rodheim-vetzberg.html
** https://www.biebertal.de/infos-tipps/gemeindedaten/geschichte/geschichte-fellingshausencopy-130copy.html
