= Fruther Bender Peppler Research Leads

== Note Others

=== On Censuses

Note the fact that certain census years show *land ownership*. Onwership implies a land purchase with resultant real property purchase record(s)--deeds,
perhaps mortgages.

Before s.o. moved, they usually sold their land. when they arrive, they purcahsed land. The purcahse may have happned before they moved.

* Note census land owernship for all ancestors, and add this this fact in my Ancestry tree. 
* Note also those from the same areas--like Beners and Pepplers--who residede next to or near one another.
* Find those ancestors and fans who had such land ownership noted on cenesuses., and the look for the land record(s)
* look for *dower release*s, appluing what you can learn from it to my ancestors.
* Look for...(whatever my reading says to note and record).

=== List in "Die Auswanderer von Rodheim a. d. Bieber", von Ernst Schmidt

Other Rühls and Platts asugewandert.

- A Henry Lepper age 65 lives near the Bender brothers according to the 1850 census. Is he from Hesse, from Rodheim?

- Many more Benders, like 15, lived in Rodheim an der Bieber. The Bender women who married are listed with their husbands (not separately). All of those mentioned by
  Ernst Schmidt emigrated. 

 - Several other Platts emigrated from Rodheim! 

How many others from Rodheim or Fellinghausen went to Allen County, Indiana? 

=== These Family Tress on Acnestry

* Thomas Bender's https://www.ancestry.com/family-tree/tree/87046752/family?cfpid=302128729037[Bender Family Tree] lists the siblings of the Bender brothersa. It has birth records for the parent's chiuldren.
* Douglas Bender's https://www.ancestry.com/family-tree/tree/160190972/family?cfpid=162100203115[Bender Family Tree]
* https://www.ancestry.com/family-tree/tree/77194369/family?cfpid=48359162578[Bender-Swank Tree]

=== FindAGrave Memorials

- https://www.findagrave.com/memorial/19337588/john-h-bender/photo[John H Bender (1835 - 1878)] of Monroeville In. Born in PA
- https://www.findagrave.com/memorial/71836544/johannes-bender[Johannes Bender (1839-1845)]]. Cemetery: Saint Paul Evangelical Lutheran Cemetery, Hessen Cassel, Allen County, Indiana

Find details on acgsi.org/genweb/cemeteries???. This is the comment from FindAGrave about Saint Paul Evangelical Lutheran Cemetery, Hessen Cassel, Allen County, Indiana:

____
Located on Thompson Road, south of I-469 and west of Marion Center Road.
Congregation moved church to 9909 Wayne Trace and changed name to Emmanuel Evangelical Lutheran Church. Mary Penrose Chapter of the DAR has a more complete listing of this cemetery, which can be accessed through the Allen County USGenWeb site.
Someone came in and poured a new foundation and placed six stones upon it. Beyond these stones, are another six or so laying flush to the ground, mostly covered with turf along their edges. According to a 1932 reading by the local DAR, there were eighteen at the time. Looking at the size of the ground covered by this cemetery, there were probably more burials than this total.
____

=== Mentioned In Other Sources

* Benders are mentioned:
  - in a 700-gate history and genalogy of the Slonaker Family. See https://shorturl.at/npqsT[page 71] for example
  - as sponsors in the Early Mohawk Valley Families https://shorturl.at/hkqy0[here]
  - in the Brenneeman History found https://shorturl.at/aisWY[on Ancestry]
  - in this Ancestry source https://shorturl.at/fknt3[Pennsylvannia Naturationzations--Povery of Immigrants]

== Get Obituaries

* Get the obituaries for Johannes and Katherine Elisabeth Rühl, and for Friedrich Bender and Elonore Christine RühlÖ two brother who married two sisters.
* Get the obituaries for Johann Bender's children, esp those born in German and for those.
* Get the obituaries for Friedrich Bender's children, esp those born in German and for those, like his son Frederick, who moved to Seward NE.

For Johann, his wife and chilfre, check the Obituary Index and local newspaper collection. They nay have been St Paul Lutheran members initially beefore Soest got u and going.

For Friedrich , his wife and sone Frederick (and any other children who settled in NE), check for the names in newspaper databases that Genealogy Center may have.

== Family Histories

Are there family histories of the Benders in the Genalogy Center already. The Pepplers?

== Local Histories and Church Histories

Check into Seward Co NE histories and any genealogical societies

== Land Records

* Genealogy Center resources

The Genealogy Center has Allen County Deed/Land records. These are just one part of its https://www.genealogycenter.info/search_microtext.php[Microtext Catalog]

** Allen Co Recorder's Office

* Its older deed book indexes (like prior to 1970 or so) can be searched online, but there is a fee since you have to use 3rd party vendor's site.

===  Church Records

* See Genealogy Center


