:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/skins 
:docinfo: shared
:docinfodir: /home/kurt/docinfo

== Peppler Research

=== TODO Next
 
The Peppler were accompanied on the ship copernicus by other families from Rodheim. those listed as emigrating in April 1857. This included:

* Dönges
* J. Kirch
* Dudenhöfer

Phlip Schwalm, who married Christine Bender (1842 - 19150), daughter of Friedrich Bender (1804-??), was also on the coperniucus, at least someone his age and with his name. 

Others from Rodheim:

Dudenhöfer , Luise Magdalene, geb. 16. 11. 1799, ausgewandert April 1857
Dudenhöfer , Katharine Elisabeth, geb. 30. 7. 1815, ausgewandert 1846
Dudenhöfer , Georg Philipp, geb. 14. 6. 1817, ausgewandert 1840 <-- Was he on the ship with Johannes Bender???
Dudenhöfer , Konrad, geb. 16. 5. 1858, ausgewandert 1882


Dudenhöfer , Johann Georg, geb. 26. 9. 1835
Weber, Anna Margaretha, geb. 22. 10. 1837, verh. 10. 8.  1862, ausgewandert im November 1863


Dudenhöfer , Johann Georg, geb. 9. 3. 1834, ausgewandert April 1857
Dudenhöfer , Andreas, geb. 4. 9. 1838, ausgewandert April 1857


*note:* Include also the Dönges from Rodhiem that may also have emigrated in April 1857 and been on the Copernicus.
