= Fruther Bender Peppler Research Leads

== Note Others

=== On Censuses

Note the fact that certain census years show *land ownership*. Onwership implies a land purchase with resultant real property purchase record(s)--deeds,
perhaps mortgages.

Before s.o. moved, they usually sold their land. when they arrive, they purcahsed land. The purcahse may have happned before they moved.

* Note census land owernship for all ancestors, and add this this fact in my Ancestry tree. 
* Note also those from the same areas--like Beners and Pepplers--who residede next to or near one another.
* Find those ancestors and fans who had such land ownership noted on cenesuses., and the look for the land record(s)
* look for *dower release*s, appluing what you can learn from it to my ancestors.
* Look for...(whatever my reading says to note and record).

=== List in "Die Auswanderer von Rodheim a. d. Bieber", von Ernst Schmidt

Other Rühlös and Platts asugewandert.

- A Henry Lepper age 65 lives near the Bender brothers according to the 1850 census. Is he from Hesse, from Rodheim?

- Many more Benders, like 15, lived in Rodheim an der Bieber. The Bender women who married are listed with their husbands (not separately). All of those mentioned by
  Ernst Schmidt emigrated. 

 - Several other Platts emigrated from Rodheim! 

How many others from Rodheim or Fellinghausen went to Allen County, Indiana? 

=== These Family Tress on Acnestry

* https://www.ancestry.com/family-tree/tree/87046752/family?cfpid=302128729037[Bender Family Tree] lists the siblings of the Bender brothersa. It has birth records for the parent's chiuldren.
* https://www.ancestry.com/family-tree/tree/160190972/family?cfpid=162100203115[Douglas Bender's Bender Family Tree]
* https://www.ancestry.com/family-tree/tree/77194369/family?cfpid=48359162578[Bender-Sqnk Tree]

=== Mentioned In Other Sources

* Benders are mentioned:
  - in a 700-gate history and genalogy of the Slonaker Family. See
  https://shorturl.at/npqsT[page 71] for example
  - as sponsors in the Early Mohawk Valley Families https://shorturl.at/hkqy0[here]
  - in the Brenneeman History found https://shorturl.at/aisWY[on Ancestry]
  - in this Ancestry source https://shorturl.at/fknt3[Pennsylvannia Naturationzations--Povery of Immigrants]

=== Obituaries

* Get the obituaries for Johannes and Katherine Elisabeth Rühl, and for Friedrich Bender and Elonore Christine RühlÖ two brother who married two sisters.
* Get the obituaries for Johann Bender's children, esp those born in German and for those.
* Get the obituaries for Friedrich Bender's children, esp those born in German and for those, like his son Frederick, who moved to Seward NE.

For Johann, his wife and chilfre, check the Obituary Index and local newspaper collection. They nay have been St Paul Lutheran members initially beefore Soest got u and going.

For Friedrich , his wife and sone Frederick (and any other children who settled in NE), check for the names in newspaper databases that Genealogy Center may have.

=== Surname File

List of meail in the surname file for Peppler, Bender, Krueckeberg, etc.

=== Family Histories

Are there family histories of the Benders in the Genalogy Center already. The Pepplers?

=== Local Histories and Church Histories

Check into Seward Co NE histories and any genealogical societies

=== Land Records

* Genealogy Center resources

The Genealogy Center has Allen County Deed/Land records. These are just one part of its https://www.genealogycenter.info/search_microtext.php[Microtext Catalog]

** Allen Co Recorder's Office

* Its older deed book indexes (like prior to 1970 or so) can be searched online, but there is a fee since you have to use 3rd party vendor's site.

===  Church Records

* See Genealogy Center


