:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/skins 
:docinfo: shared
:docinfodir: /home/kurt/docinfo

== Bender Research

There is a Bender family history in the Genealoy Center written by a late Allen County resident. It was published around 1972:

* https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/196432?offset=4&qs=Bender&search_in=iets&sortkey=titel&state=search&wf_onderwerp=Bender%20family&wf_vestlabel=Genealogy[The Bender Family Story]
  Call number: *929.2 B43171fi*. Published: 1971

Contents: Great grandfather -- America -- Eighteen thirty seven -- They came to Indiana -- Eigheteen forty -- Hessen Castle -- Eighteen fifty cenus -- Called home -- Phillip -- John Jacob dies -- Final words.

* https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/330333?offset=3&qs=Bender&search_in=iets&sortkey=titel&state=search&wf_onderwerp=Bender%20family&wf_vestlabel=Genealogy[Bender-Bainter-Painter Smith and the allied families of Phillipson, Marino, Alioto]

Create a timeline for the Benders that includes their facts and events on FamilySearch and Ancestry, each accompanbied by a source citation. Using such a timeline will help clarify what questions need to be researched.

There are other records yet to investigate include those mention below.


=== Other Rodheim/Fellinhausen Emigrants in Marion Twp, Allen CO. Indiana

In 1857, when the Pepplers emigrated, they were accompanied on the ship Copernicus by other families from Rodheim. Those listed by link:./die-auswanderer-aus-kirchspiel-rodheim.pdf[Ernst Schmidt] as
emigrating in April 1857 included:

* Dönges
* J. Kirch
* Dudenhöfer

Philip Schwalm, who married Christine Bender (1842 - 19150), daughter of Friedrich Bender (1804-??), was also listed on the passenger list of the Copernicus
(or at least someone his age and with his name).

Those from Rodheim who emigrated in April 1857 were:

Dudenhöfer , Luise Magdalene, geb. 16. 11. 1799, ausgewandert April 1857
Dudenhöfer , Katharine Elisabeth, geb. 30. 7. 1815, ausgewandert 1846
Dudenhöfer , Georg Philipp, geb. 14. 6. 1817, ausgewandert 1840 <-- Was he on the ship with Johannes Bender???
Dudenhöfer , Konrad, geb. 16. 5. 1858, ausgewandert 1882

Dönges ?????

Dudenhöfer , Johann Georg, geb. 26. 9. 1835
Weber, Anna Margaretha, geb. 22. 10. 1837, verh. 10. 8.  1862, ausgewandert im November 1863

Dudenhöfer , Johann Georg, geb. 9. 3. 1834, ausgewandert April 1857
Dudenhöfer , Andreas, geb. 4. 9. 1838, ausgewandert April 1857

*Note:* Include also the Dönges from Rodhiem that may also have emigrated in April 1857 and been on the Copernicus.


The 1867 Allen County Indiana, https://www.ancestry.com/discoveryui-content/view/1440232475:2469?tid=68081704&pid=38213189245&hid=1007410371314&_phsrc=KtD1474&_phstart=default[City Directory] lists individuals from
Rodheim an der Bieber und Fellinghausen:

Benders, three Fredericks
Bender, George
Bender, John
Bender, Louis
Peppler, Jacob
Peppler, Louis
Dudenhafers, two or three
Dinges
Ahlschwede, Frederick
=== TODO Next

Add the newpaper article images (and transcribe them) for *Christine nee Bender Schwalm* since it mentions family members. There might be details about her parents. This is unlikely, as her obit would her obituary
wd be the most likely src of this info. But theese articles do provide details that might proven fruitful in the future.

Read also the Bender Family Hitory mentioned below.

Christine Bender (1842 - 1915), daughter of ?? Bender, married Philip Schwalm. A Philip Schwalm arrived on the same boat, the Copernicus, as the Johann Jokob Peppler family, according to its
https://bit.ly/3Q0Fa0C[passenger list]. 

=== Bender-Felt Relationships

A 24 Aug 1922 Journal Gazette link:felt-bender-reunion-24-Aug-1922-JG.pdf[article] describes the Bender-Felt reunion. It mentions many individuals in attendence, and thus relationships between many
families can be inferred. There is also a high-resolution link:felt-bender-reunion-24-aug-1922-JG.jpg[image].

=== PDFs fo Newspaper Articles

There are several PDFs in this folder of Bender (and others)-related articles to investigate.

=== Other Records to Explore Include

Was this individual on the ship with thethe Johannes Bender family in 1840?

Dudenhöfer , Georg Philipp, geb. 14. 6. 1817, ausgewandert 1840 

Find it again.

==== Genealoy Center Family Histories
==== Deeds, Plats, Tracks

Finding all deeds for Johannes and Joahnn Freidrich Bender, who both own land they farmed according to the 1850 Census, in Marion Twp, Allen County.

Deeds of sale of this land before they moved to Adams township and purchased other land--unless the township borders changed.
Therefore, I should seek to find this land also from *Platts* -- orignal surveys and any later -- that would show the land they owned; or from *Tract books*.

Later probate records that describe anything of relevant to this land

==== Tax Lists

Are there any that might be available.

==== Probated Wills

Ancestry has probated will of Frederick Bender (1837 to 1918), the son of Johann Friedrich Bender's (1804 to 187?). Its link:./Frederick_Bender_1837-to-1918_Probated_will.png[image] is legible and mentions: 

* Frederick's wife and
* two of his sons that reside in Seward Co, Nebraska, and
* it was winessed by two individuals whose surname is *Ahlschwede* and one whose surname is *Frank*.

*Comment:* The first Ahlschwedes in Seward Co. NE came from Allen Co. IN, https://www.findagrave.com/memorial/63679060/wilhelm-ahlschwede[Wilhelm “William” Ahlschwede]. The late Dolores Kulkuchi's
https://www.ancestry.com/family-tree/tree/27940543/family?cfpid=5097750032[Koch-Starke-Alschwede-etc Tree] includes Ahlschwedes that settled in Allen and Adams Counties and in Huntington Indiana.

==== Church Records

The Sankt Johannis Gemeinde church book will be helpful because https://www.ancestry.com/family-tree/person/tree/68081704/person/38213189248/facts[Eleonore Bender (1833 to 1861)],
the daughter of Johanes Bender and Katharine Elisabeth Rühl(1809-1897), was recorded as buried in the Sankt Johanis Gemeinde Friedhof by the Mary Pensoe DAR chapter (I believe). This
suggests her parents were also members.

And the Soest records will also be helpful.

==== NE Death Index

This https://www.ancestry.com/discoveryui-content/view/415557:62095?tid=68081704&pid=122395610254&hid=1007362676017[image] from the "Nebraska, U.S., Index to Deaths, 1904-1968", shows several Benders who died, including
Frederick Bender (1837-1918).

==== Allen County Obituries

See these obituaries:

include::./obits-benders-others.adoc[]
