*Key to abbreviations:*

* a = age at death
* abt = about
* ad = additional
* adm = administrator
* app = appointed
* b = born
* br = brother
* cem = cemetery
* ch = [context sensitive] children or church
* City = Fort Wayne, IN
* d = [context sensitive] death or day(s)
* dau = daughter
* Ex = executor
* f = funeral
* fa = father
* g = grand
* gg = great grand
* h = husband
* inf = [context sensitive] infant or infirmary
* int = interred
* m = [context sensitive] month(s) or married
* mo = mother
* nat = native

* PD = paper date
* Pres = Presbyterian
* pro = probate or probated
* rd = road
* res = resides
* s = son
* S = south
* ser = service
* sis = sister
* sur = survive
* t = township
* unm = unmarried
* w = [context sensitive] wife or week(s)
* wid = widow
* y = year
* ~~ = separates the data elements

*Newspapers*

* FWDD = Fort Wayne Daily Democrat
* FWDG = Fort Wayne Daily Gazette
* FWDJ = Fort Wayne Daily Journal
* FWDN = Fort Wayne Daily News
* FWDS = Fort Wayne Daily Sentinel
* FWDT = Fort Wayne Daily Times
* FWJ = Fort Wayne Journal
* FWMG = Fort Wayne Morning Gazette
* FWMJ = Fort Wayne Morning Journal
* FWS = Fort Wayne Sentinel
* FTSt = Fort Wayne Standard
* FWT = Fort Wayne Times

* FWTP = Fort Wayne Times & Peoples Press
* FWWD = Fort Wayne Weekly Democrat
* FWWS = Fort Wayne Weekly Sentinel
* JEFF = Jeffersonian

Researchers can find microfilm of all of the Fort Wayne newspapers in
the Allen County Public Library's Genealogy Center. Copies of specific
obituaries may be ordered by emailing
mailto:genealogy@acpl.info?subject=Obituary%20Request[Genealogy@ACPL.Info]
with the complete citation as found in the index. Cost is $2.50 per
obituary, billed at the time of mailing. Response time is typically 4-6
weeks. Your complete name and mailing address must be included with your
request.

This index was taken from Fort Wayne and Allen County, IN Area Obituary
Index, 1841-1899, and *not taken from the microfilm copies found in the
Allen County Public Library's Genealogy Center*. Meant to abstract
information found in the obituary, the specific newspaper title, page
number, and meaning of the date (death, obituary, probate, etc.) often
are not indicated. Reasonable efforts will be made to locate and copy
these obituaries, but the volunteers and staff of the Genealogy Center
cannot guarantee that the original obituaries will be found.

[#anchor]####****

.Benders 
[cols=",,,",]
|===
|Surname |First Name |Obituary Date |Notes

|BENDER |14 D/o Child Of Samuel |02/05/1895 |FWDN p. 4

|BENDER |18 M/o Child Of William |07/22/1899 |FWDS p. 4

|BENDER |2 W/o Child Of Samuel |02/05/1895 |FWDS p. 1

|BENDER |4 M/o Child Of Christopher |01/15/1890 |FWS p. 4

|BENDER |Adam |06/07/1872 |FWDS p. 4

|BENDER |Adam |06/07/1872 |FWS p. 4

|BENDER |Child Of W.c. |03/08/1893 |FWWS p. 7

|BENDER |Christopher (Dau Of) |01/15/1890 |d~~Creighton Ave

|BENDER |Dennis |08/06/1895 |FWDN p. 1

|BENDER |Dennis |08/06/1895 |FWDS p. 1

|BENDER |Edith |07/22/1889 |FWDN, p. 1; d~~216 Francis St, inf dau of
John

|BENDER |Elizabeth |01/27/1892 |d~~a 47y~~w of Peter...native of Pa.,
O...m 3 times...1st h, Higgins..ch of; Mrs. Netterfield, Wells Co.
(Emma); James Higgins, Greenfield, Ind & Melissa Higgins, City...2nd h
Mr. Bowers

|BENDER |Elizabeth |02/03/1892 |FWWS p. 3

|BENDER |Elizabeth |02/03/1892 |FWWS, p 1,

|BENDER |Frances |05/15/1887 |d~~a 19y~~w of Levi, 169 Clinton

|BENDER |George |02/03/1894 |FWDS p. 1

|BENDER |George |02/04/1894 |FWDG, p. 8; d~~a 50y~~205 Francis St...w &
3 ch sur

|BENDER |George |02/10/1894 |FWDS p. 1

|BENDER |Howard |06/27/1887 |FWDS, p. 4; age 5, son of Levi

|BENDER |Jackson |07/03/1871 |FWDS p. 2

|BENDER |Jackson |07/03/1871 |FWS p. 2

|BENDER |John |04/21/1886 |FWDS, p. 1; F Friday

|BENDER |Katherina |03/13/1897 |FWDS p. 4

|BENDER |Katherina |03/15/1897 |FWDS p. 1

|BENDER |Katherine, Mrs. |03/14/1897 |FWDG, p. 8; d~~a 88y~~s, Louis
Bender, Adams T

|BENDER |Louis (Ch Of) |12/00/1876 |d~~

|BENDER |Louis (Ch Of) |05/22/1881 |d~~E Washington St

|BENDER |Magdeline |04/26/1886 |DWDN, p. 1

|BENDER |Mary E. |01/20/1890 |FWS p. 2

|BENDER |Mrs. Peter [elizabeth] |02/03/1892 |FWWS p. 1

|BENDER |Philip |04/24/1890 |FWDG, p. 4; d~~Richmond Road (9 miles)...w
& 4 ch sur...s-in-law, Fred Brabse, W. Jefferson St

|BENDER |Philip T. |04/24/1890 |FWS p. 4

|BENDER |Reuben |09/06/1894 |FWDS p. 1

|BENDER |Reuben |09/10/1894 |f~~77 Grand St...Berry St. M. E. Church

|BENDER |Ruben |09/06/1894 |FWDN p. 1

|BENDER |Samuel (Ch Of) |02/04/1895 |d~~a 14d~~69 Gay St

|BENDER |Samuel, Mrs. |02/05/1895 |FWDS, p. 1

|BENDER |Susie, Mrs. |08/11/1878 |d~~dau of Mrs. Flynn, W. Wayne St...d
in Pa...int; Lindenwood

|BENDER |W. C. (Ch Of) |03/04/1893 |d~~a 3d~~143 Griffith St...int;
Zanesville, Ind

|BENDER |William |07/20/1892 |FWWS p. 4

|BENDER |William |07/21/1892 |d~~a 4y~~63 E Main St

|BENDER |Willie |07/27/1892 |FWWS p. 4

|BENDER |Wm. (Young Ch Of) |11/30/1888 |f~~173 W Washington St...int;
Sheldon

|BUTTONBENDER |Henry |12/17/1882 |d~~a 66y~~187 W Washington
|===

TODO: Using the death date of those below, look up the obituary, if any,
in * from the microfilm copies found in the Allen County Public
Library's Genealogy Center..*

**

== *Allen County, Indiana Church Burial Records*

Databse includes these churches:

* Cath =
https://www.genealogycenter.info/data_churchburialscath.php[Catholic
Cemetery Burial Records before 1873]
* Cathedral =
https://www.genealogycenter.info/data_churchburialscathedral.php[Cathedral
of the Immaculate Conception, Fort Wayne]
* EmmLuth =
https://www.genealogycenter.info/data_churchburialsemmluth.php[Emmanuel
Lutheran, Marion Township]
* MartLuth =
https://www.genealogycenter.info/data_churchburialsmartluth.php[Martini
Lutheran, Fort Wayne (now New Haven)]
* SJUCC =
https://www.genealogycenter.info/data_churchburialssjucc.php[St. John's
United Church of Christ, Fort Wayne]
* SMC = https://www.genealogycenter.info/data_churchburialssmc.php[St.
Mary's Catholic Church, Fort Wayne]
* SPatC =
https://www.genealogycenter.info/data_churchburialsspatc.php[St.
Patrick's Catholic Church, Arcola]
* SPaulC =
https://www.genealogycenter.info/data_churchburialsspaulc.php[St. Paul's
Catholic Church, Fort Wayne]
* SPaulL =
https://www.genealogycenter.info/data_churchburialsstpaullutheran.php[St.
Paul's Evangelical Lutheran Church, Fort Wayne]

* StMarkLuth =
https://www.genealogycenter.info/data_churchburialsstmarkluth.php[St.
Mark's Evangelical Lutheran Church, Pleasant Township]
* StPeterLth =
https://www.genealogycenter.info/data_churchburialsstpeterlth.php[St.
Peter's Evangelical Lutheran Church, St. Joseph Township]
* StJosC =
https://www.genealogycenter.info/data_churchburialsstjosc.php[St. Joseph
Hessen Cassel Catholic, Marion Township]
* StLBC =
https://www.genealogycenter.info/data_churchburialsstlbc.php[St. Louis
Besancon Catholic, New Haven]
* TEEL =
https://www.genealogycenter.info/data_churchburialsteel.php[Trinity
English Evangelical Lutheran Church, Fort Wayne]
* TrinE =
https://www.genealogycenter.info/data_churchburialstrine.php[Trinity
Episcopal, Fort Wayne]
* TrinSbLuth =
https://www.genealogycenter.info/data_churchburialstrinsbluth.php[Trinity
Suburban Evangelical Lutheran Church, Fort Wayne]

[#anchor-1]##

[cols=",,,,",]
|===
|Surname |First Name |Date of Burial |Other Information |Church

|Hekeler |Barbara |18 Sep 1881 |nee Rauch, w/o Thomas Hekeler, b. 24 Jul
1787 in Enzweihingen, Vaihingen, Wurttemberg, d. 15 Sep 1881.
|StMarkLuth

|Hisler |Mary Catherine |00 Aug 1843 |d/o Bernard Hisler and Christine
Bashorn. |Cathedral
|===

**
