:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/skins 
:docinfo: shared
:docinfodir: /home/kurt/docinfo

== Bender Research

Create a timeline for the Benders that includes their facts and events on FamilySearch and Ancestry, each accompanbied by a source citation. Using such a timeline will help clarify what questions need to be researched.

There are other records yet to investigate include those mention below.

=== Other Records to Explore Include

==== Uncited FS Story

Find it again.

==== Genealoy Center Family Histories

* https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/196432?offset=4&qs=Bender&search_in=iets&sortkey=titel&state=search&wf_onderwerp=Bender%20family&wf_vestlabel=Genealogy[The Bender Family Story]
  Call number: *929.2 B43171fi*. Published: 1971

Contents: Great grandfather -- America -- Eighteen thirty seven -- They came to Indiana -- Eigheteen forty -- Hessen Castle -- Eighteen fifty cenus -- Called home -- Phillip -- John Jacob dies -- Final words.

* https://acpl.lib.in.us/wise-apps/catalog/6000/detail/wise/330333?offset=3&qs=Bender&search_in=iets&sortkey=titel&state=search&wf_onderwerp=Bender%20family&wf_vestlabel=Genealogy[Bender-Bainter-Painter Smith and the allied families of Phillipson, Marino, Alioto]

==== Deeds, Plats, Tracks

Finding all deeds for Johannes and Joahnn Freidrich Bender, who both own land they farmed according to the 1850 Census, in Marion Twp, Allen County.

Deeds of sale of this land before they moved to Adams township and purchased other land--unless the township borders changed.
Therefore, I should seek to find this land also from *Platts* -- orignal surveys and any later -- that would show the land they owned; or from *Tract books*.

Later probate records that describe anything of relevant to this land

==== Tax Lists

Are there any that might be available.

==== Probated Wills

Ancestry has probated will of Frederick Bender (1837 to 1918), the son of Johann Friedrich Bender's (1804 to 187?). Its link:./Frederick_Bender_1837-to-1918_Probated_will.png[image] is legible and mentions: 

* Frederick's wife and
* two of his sons that reside in Seward Co, Nebraska, and
* it was winessed by two individuals whose surname is *Ahlschwede* and one whose surname is *Frank*.

*Comment:* There were Ahlschwde 's in Allen County. The late Dolores Kulkuchi's https://www.ancestry.com/family-tree/tree/27940543/family?cfpid=5097750032[Koch-Starke-Alschwede-etc Tree] includes Ahlschwedes that
settled in Allen and Adams Counties and in Huntington Indiana.

==== Church Records

The Sankt Johannis Gemeinde church book will be helpful because https://www.ancestry.com/family-tree/person/tree/68081704/person/38213189248/facts[Eleonore Bender (1833 to 1861)],
the daughter of Johanes Bender and Katharine Elisabeth Rühl(1809-1897), was recorded as buried in the Sankt Johanis Gemeinde Friedhof by the Mary Pensoe DAR chapter (I believe). This
suggests her parents were also members.

And the Soest records will also be helpful.

==== NE Death Index

This https://www.ancestry.com/discoveryui-content/view/415557:62095?tid=68081704&pid=122395610254&hid=1007362676017[image] from the "Nebraska, U.S., Index to Deaths, 1904-1968", shows several Benders who died, including
Frederick Bender (1837-1918).

==== Allen County Obituries

See these obituaries:

include::./obits-benders-others.adoc[]
