=== Obituaries

* Get the obituaries for Johannes and Katherine Elisabeth Rühl, and for Friedrich Bender and Elonore Christine RühlÖ two brother who married two sisters.
* Get the obituaries for Johann Bender's children, esp those born in German and for those.
* Get the obituaries for Friedrich Bender's children, esp those born in German and for those, like his son Frederick, who moved to Seward NE.

For Johann, his wife and chilfre, check the Obituary Index and local newspaper collection. They nay have been St Paul Lutheran members initially beefore Soest got u and going.

For Friedrich , his wife and sone Frederick (and any other children who settled in NE), check for the names in newspaper databases that Genealogy Center may have.

=== Surname File

List of meail in the surname file for Peppler, Bender, Krueckeberg, etc.

=== Family Histories

Are there family histories of the Benders in the Genalogy Center already. The Pepplers?

=== Local Histories and Church Histories

Check into Seward Co NE histories and any genealogical societies

=== Land Records

* Genealogy Center resources

The Genealogy Center has Allen County Deed/Land records. These are just one part of its https://www.genealogycenter.info/search_microtext.php[Microtext Catalog]

** Allen Co Recorder's Office

* Its older deed book indexes (like prior to 1970 or so) can be searched online, but there is a fee since you have to use 3rd party vendor's site.

===  Church Records

* See Genealogy Center


