=== FamilySearch wiki German Research Section

=== German Verein Liste

GenWiki's link:https://wiki.genealogy.net/Portal:Vereine[Portal von Vereine]

____
Viele genealogische Vereine, Arbeitskreise, Interessengemeinschaften und andere genealogische Institute stellen sich auf dem Server des Vereins für Computergenealogie e.V. vor und nehmen aktiv an den Projekten teil.
Auch wenn Sie vielleicht sonst ein Vereinsmuffel sind, die Mitgliedschaft in einem genealogischen Verein kann sich lohnen! Viele genealogische Veranstaltungen werden von Vereinen ausgerichtet. Mitglieder einiger
Vereine, Arbeitsgruppen usw., die hier im GenWiki eine Anmeldung und damit eine Benutzerseite haben, teilen ihre Mitgliedschaft dort mit, die Übersicht dazu findet sich hier. 
____

Vereins of note: 

- Hamburg

- Bremen

- Niedersachsen. See links and descriptions at link:https://wiki.genealogy.net/Nieders%C3%A4chsischer_Landesverein_f%C3%BCr_Familienkunde_e.V._(NLF[Niedersächsicher Landesverein für Familenkunde]

- link:https://www.vfkbw.de/[Verein für Familienkunde in Baden-Württemberg]

- link:https://www.hfv-ev.de/[Hessische familiengeschichtliche Vereinigung (HfV)]

- Schaumburg TODO

=== Hesse

include::./hesse.adoc[]

=== Niedersachsen/Schaumburg

=== Kirchenbücher

- Kirchenbücher der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe haben zur Verfügung gestellt. Das heiß, dass man die Kirchenbücher für die folgende Städte 

* Altenhagen-Hagenburg
* Bergkirchen
* Bückeburg
* Frille
* Heuerßen
* Lauenhagen
* Lindhorst
* Meerbeck
* Meinsen
* Petzen
* Probsthagen
* Stadthagen
* Steinbergen
* Steinhude
* Sülbeck
* Vehlen

im Internet sehen kann.

The Petzen, Schamburg, Lower Saxony, church records are now available online (for a fee) at Archion.de Church Portal. To navigagte to them, choose Browse -> 
Niedersachsen: Niedersächsisches Landesarchiv -> Kirchenbücher der Evangelisch-Lutherischen Landeskirche Schaumburg-Lippe -> Petzen. These church records are included: 
 
* Altenhagen-Hagenburg
* Bergkirchen
* Bückeburg
* Frille
* Heuerßen
* Lauenhagen
* Lindhorst
* Meerbeck
* Meinsen
* Petzen
* Probsthagen
* Stadthagen
* Steinbergen
* Steinhude
* Sülbeck
* Vehlen

- Niedersachsen: Landeskirchliches Archiv Hannover -> Kirchenkreis Holzminden; you will see it is not in green, meaning it is not vailable (as of 09/12/2022)..
