:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/skins 
:docinfo: shared
:docinfodir: /home/kurt/docinfo

== Heckeler Haeckler Fmaily

Todo:

- There is a source, hint, on Acnestry, for the arrival of the Heckelers. The origial supposedly contains (or mentions the collection of ship names) from which the dta was taken.

* The "facts" for Heckelers are inacurrate. They do not reflect the actual facts--village, city, district, etc--in the associated records.

* The Heckeler Haeckler Family is extensively documented in the FamilySearch Tree, going back far into the 18th century in Württemburg. 
  See, for example, the person-entry for 
  https://www.familysearch.org/tree/pedigree/landscape/LCX4-2C6[Christian Heckler(17370-1795)], the father of 
  - Johann Thomas Heckler/Haeckler/Hecheler, who
  married Maria Barbara Rauch, who was the father of https://www.ancestry.com/family-tree/person/tree/68081704/person/122401939145/facts[Johann Christoph "Christopher" Heckeler],
  whose https://www.ancestry.com/imageviewer/collections/48324/images/HudsonMohawkII-002839-892?pId=292090[biography] appears in the Mohawk-Hudson Valley volume of biographies. 

This biography says that Johann Thomas Haeckler emigrated in 1840, departing Bremen and arriving in NYC 90 days later, and he obtained a land patent to land in Pleasant township, 
Allen County IN. 

I don't believe I have the correct city of origin for the family. It should be based on the church records. I think I need to find them on FamilySearch, Württemburg Familie Regist????try
and maybe Archion (or equivalent public site).
